akveo/nebular

- src/framework/theme/components/menu/menu-item.component.html
> Support hidden property

- .travis.yml
> fix(travis): stop randomly failing builds

- .travis.yml
> build(travis): playing with travis config

- CONTRIBUTING.md
> docs(readme): add release commit status

- .travis.yml
> fix(travis): remove git depth to allow commits comparison

- e2e/layout-header.e2e-spec.ts
- src/framework/theme/components/layout/layout.component.scss
> fix(header): fix layout header test

- docs/app/app.component.ts
- docs/app/docs/docs.service.ts
- e2e/actions.e2e-spec.ts
- e2e/flip-card.e2e-spec.ts
- e2e/reveal-card.e2e-spec.ts
- e2e/user.e2e-spec.ts
- src/app/app.module.ts
- src/app/layout-test/theme-breakpoint-test.component.ts
- src/framework/theme/components/badge/badge.component.ts
- src/framework/theme/components/card/flip-card/flip-card.component.ts
- src/framework/theme/components/card/shared/shared.component.ts
- src/framework/theme/components/menu/menu.component.ts
- src/framework/theme/components/menu/menu.service.ts
- src/framework/theme/components/shared/shared.module.ts
- src/framework/theme/services/js-themes-registry.service.ts
- tslint.json
>  refactor: remove unused vars, fix linter

- e2e/badge.e2e-spec.ts
- e2e/card.e2e-spec.ts
- e2e/e2e-helper.ts
> Fix case when browser lag during rendering element

- e2e/search.e2e-spec.ts
- src/framework/theme/components/search/search.component.ts
> fix(search): fix tests some time not passing on search

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/auth/package.json
- src/framework/theme/package.json
> release: bump to 2.0.0-rc.5

- docs/output.json
- src/framework/theme/components/search/search.component.ts
> fix(search): fix search not un-subscribing from events

- src/framework/theme/components/card/flip-card/flip-card.component.ts
> fix(docs): use correct tag in usage example

- docs/output.json
- e2e/checkbox.e2e-spec.ts
- src/app/app.module.ts
- src/app/app.routes.ts
- src/app/checkbox-test/checkbox-test.component.ts
- src/framework/theme/components/checkbox/_checkbox.component.theme.scss
- src/framework/theme/components/checkbox/checkbox.component.ts
- src/framework/theme/components/checkbox/checkbox.spec.ts
- src/framework/theme/styles/themes/_cosmic.scss
- src/framework/theme/styles/themes/_default.scss
> Add theme variables for nb-checkbox

- docs/output.json
- docs/structure.ts
- src/framework/security/services/access-checker.service.ts
> docs(security): add security services to the docs

- DEV_DOCS.md
> add npm command example

- src/framework/theme/components/popover/_popover.component.theme.scss
- src/framework/theme/components/popover/popover.component.scss
- src/framework/theme/components/popover/popover.component.ts
- src/framework/theme/styles/themes/_default.scss
Add popover border radius theme variable
> feat(popover): add popover-border-radius theme var

- src/framework/theme/components/popover/_popover.component.theme.scss
- src/framework/theme/components/popover/popover.component.scss
- src/framework/theme/components/popover/popover.component.ts
- src/framework/theme/styles/themes/_default.scss
> Revert "feat(popover): add popover-border-radius theme var"

- DEV_DOCS.md
- src/app/bootstrap-test/bootstrap-test.component.ts
- src/framework/theme/components/checkbox/_checkbox.component.theme.scss
- src/framework/theme/styles/global/bootstrap/_bootstrap.theme.scss
- src/framework/theme/styles/global/bootstrap/_checkbox.scss
- src/framework/theme/styles/global/bootstrap/_custom-forms.scss
- src/framework/theme/styles/global/bootstrap/_nb-form-theme.scss
> Bootstrap checkbox and radio styles according bootstrsap 4.0.0

- CHANGELOG.md
- docs/output.json
- package-lock.json
- package.json
- src/framework/auth/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 2.0.0-rc.6

- src/app/popover-test/popover-test.component.ts
- src/framework/theme/components/popover/popover.directive.ts
> fix(popover): run markForCheck to detect changes if nb-layout has onPush

- docs/articles/auth-guard.md
Change provoders to providers.
> Fix typo in auth-guard docs

- DEV_DOCS.md
> docs(dev-docs): add a note about publishing of docs

- docs/app/app.module.ts
- docs/app/docs/docs.service.ts
- docs/app/docs/page/blocks/basic-blocks/ngd-description-block.component.ts
- docs/app/docs/page/blocks/basic-blocks/ngd-examples-block.component.ts
- docs/app/docs/page/blocks/basic-blocks/ngd-methods-block.component.ts
- docs/app/docs/page/blocks/basic-blocks/ngd-props-block.component.ts
- docs/app/docs/page/blocks/basic-blocks/ngd-styles-block.component.ts
- docs/app/docs/page/blocks/ngd-block.component.ts
- docs/app/docs/page/blocks/ngd-component-block.component.ts
- docs/app/docs/page/blocks/ngd-markdown-block.component.ts
- docs/app/docs/page/blocks/ngd-theme-block.component.ts
- docs/app/docs/page/page.component.ts
- docs/structure.ts
- Block switch was moved in the separate component - ngd-block.
- blockData property of the component blocks was renamed to the source like in the other block types, for consistency.
> Docs: code improvements

- docs/articles/auth-token.md
> docs(auth): fix incorrect token mention

- .travis.yml
> chore(travis): update browser stack error

- src/framework/auth/providers/email-pass-auth.provider.ts
- src/framework/auth/providers/email-pass-auth.spec.ts
> test(auth): email pass auth provider test

- docs/app/docs/page/blocks/basic-blocks/ngd-props-block.component.ts
- docs/app/docs/utils/block-helper.service.ts
- src/framework/theme/components/menu/menu.component.ts
- src/framework/theme/components/menu/menu.service.ts
> docs(menu): add `NbMenuItem` documentation

- docs/articles/install-starter-kit.md
> docs(install): remove mention of start:prod

- package.json
- src/framework/theme/theme.module.ts
> fix(theme): fix window and document providers to work in AOT

- src/framework/theme/theme.module.ts
> refactor: use document provided by angular

- src/polyfills.ts
> fix: add polyfills for IE (es7 array & object)

- src/framework/theme/components/context-menu/context-menu.directive.ts
> fix(docs): add context-menu item click handler example

- docs/app/docs/page/blocks/tabbed-block/ngd-tabbed-block.component.scss
> fix(docs): return missed section anchors

- docs/articles/auth-ui.md
> fix(docs): fix incorrect component mention

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/auth/package.json
- src/framework/security/package.json
- src/framework/theme/components/context-menu/context-menu.directive.ts
- src/framework/theme/package.json
> release: 2.0.0-rc.7

- DEV_DOCS.md
> docs(DEV_DOCS): ngx-admin deployment update

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/auth/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 2.0.0-rc.8 (RTL & Angular 6+ support)

- src/framework/auth/UPGRADE.md
> chore(auth): update upgrade guide

- e2e/popover.e2e-spec.ts
- src/framework/theme/components/popover/popover.directive.ts
> fix(popover): hide when host was removed

- docs/app/@theme/services/index.ts
- docs/app/@theme/services/pagination.service.ts
- docs/app/@theme/services/structure.service.ts
- docs/app/@theme/theme.module.ts
- docs/app/blocks/blocks.module.ts
- docs/app/blocks/components/index.ts
- docs/app/blocks/components/pager-block/pager-block.component.scss
- docs/app/blocks/components/pager-block/pager-block.component.ts
- docs/app/documentation/documentation.component.ts
- docs/app/documentation/menu.service.ts
- docs/app/documentation/page/page.component.html
- docs/app/documentation/page/page.component.ts
> feat(docs): add pagination block

- e2e/popover.e2e-spec.ts
- src/app/app.module.ts
- src/app/app.routes.ts
- src/app/popover-test/popover-test.component.ts
> fix(playground): rollback popover tests

- src/framework/theme/components/layout/_layout.component.theme.scss
> fix(layout): fix layout height with header is not fixed

- src/framework/theme/components/search/search.component.ts
> fix(search): resolve search field component factory

- src/framework/theme/components/card/reveal-card/reveal-card.component.scss
> fix(reveal-card): fix second card being visible on small screens

- docs/app/@theme/components/fragment-target/fragment-target.directive.ts
- docs/app/blocks/components/pager-block/pager-block.component.ts
- docs/app/blocks/components/theme-block/theme-block.component.html
- docs/app/blocks/components/theme-block/theme-block.component.scss
- docs/app/blocks/components/theme-block/theme-block.component.ts
- docs/app/blocks/components/theme-block/theme-block.model.ts
- docs/app/blocks/components/theme-block/theme-block.viewmodel.ts
> Add the themes block

- src/framework/theme/components/card/flip-card/flip-card.component.ts
- src/framework/theme/components/card/reveal-card/reveal-card.component.ts
> feat(card): option to hide toggle button in reveal/flip cards

- src/framework/theme/components/layout/_layout.component.theme.scss
> fix(footer): use correct footer color variable

- src/framework/theme/services/theme.service.ts
> docs(theme): add missed theme.service methods

- docs/app/@theme/components/header/header.component.scss
- docs/app/blocks/components/components-overview-block/components-overview-block.component.scss
- docs/app/blocks/components/live-example-block/live-example-block.component.html
- docs/app/blocks/components/live-example-block/live-example-block.component.scss
Safari iframe overflow and zooming fixes. Increase sidebar toggle button.
> feat(docs): overflow fixes

- docs/structure.ts
> fix(docs): add progress-bar icon

- src/framework/theme/components/menu/menu.component.ts
- src/framework/theme/components/menu/menu.service.ts
> feat(menu): add collapseAll function

- docs/app/@theme/components/footer/footer.component.html
- docs/app/@theme/components/footer/footer.component.scss
- docs/app/@theme/components/header/header.component.scss
- docs/app/@theme/components/hero/hero.component.scss
- docs/app/documentation/page/page.component.scss
> fix(docs): update mobile styles

- docs/app/@theme/services/text.service.ts
- docs/app/documentation/page/page.component.html
- docs/app/documentation/page/page.component.scss
- docs/app/documentation/page/page.component.ts
- docs/articles/auth-guard.md
- docs/articles/auth-install.md
- docs/articles/auth-intro.md
- docs/articles/auth-strategy.md
- docs/articles/auth-token.md
- docs/articles/auth-ui.md
- docs/articles/backend-integration.md
- docs/articles/concept-3rd-party.md
- docs/articles/concept-theme-system.md
- docs/articles/concept-ui-kit.md
- docs/articles/enabling-theme-system.md
- docs/articles/index.md
- docs/articles/install-into-existing.md
- docs/articles/install-starter-kit.md
- docs/articles/security-install.md
- docs/articles/security-intro.md
- docs/articles/server-deployment.md
- docs/articles/start.md
- package.json
> feat(docs): update urls to include baseUrl

- README.md
- docs/articles/auth-oauth2.md
- docs/structure.ts
- src/framework/auth/auth.module.ts
- src/framework/auth/strategies/index.ts
- src/framework/auth/strategies/oauth2/oauth2-strategy.spec.ts
- src/framework/auth/strategies/oauth2/oauth2-strategy.ts
- src/playground/oauth2/oauth2-callback.component.ts
- src/playground/oauth2/oauth2-login.component.ts
- src/playground/oauth2/oauth2.module.ts
- src/playground/playground-routing.module.ts
> feat(auth): add oauth2 example with google auth

- src/framework/icons/css/nebular-icons.css
- src/framework/icons/scss/_nebular-icons-font.scss
- src/framework/theme/styles/themes/_corporate.scss
> fix(theme): remove layout-padding for corporate theme, remove unnecessary color from icon

- src/framework/icons/package.json
> release: 1.0.8 of nebular-icons

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/auth/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 2.0.0-rc.9

- docs/app/@theme/services/analytics.service.ts
- docs/app/blocks/components/tabbed-block/tabbed-block.component.ts
- docs/app/example/example.component.ts
- docs/index.html
> fix(docs): update analytics tracking to exclude duplicated events

- src/playground/popover/popover-placements.component.html
- src/playground/popover/popover-placements.component.ts
- src/playground/popover/popover-showcase.component.html
> fix(docs): fix popover examples

- docs/app/home/home.component.ts
> fix(docs): add a note about new theme

- docs/app/app.module.ts
- docs/app/blocks/components/stacked-example-block/stacked-examples.component.ts
> feat(docs): add example change animation

- src/framework/auth/package.json
- src/framework/security/package.json
> fix: fix peer dependency rxjs version

- src/framework/auth/components/auth.component.scss
- src/framework/auth/components/auth.component.ts
> feat(auth): add back button

- docs/app/app.module.ts
- src/framework/theme/components/button/button.component.scss
- src/playground/accordion/accordion-toggle.component.html
- src/playground/menu/menu-test.component.ts
- src/playground/oauth2-password/oauth2-password-login.component.ts
- src/playground/oauth2/oauth2-login.component.ts
- src/playground/playground.module.ts
- src/playground/popover/popover-custom-component.component.html
- src/playground/popover/popover-custom-component.component.ts
- src/playground/popover/popover-modes.component.html
- src/playground/popover/popover-placements.component.html
- src/playground/popover/popover-placements.component.ts
- src/playground/popover/popover-showcase.component.html
- src/playground/popover/popover-template-ref.component.html
- src/playground/popover/popover-test.component.ts
- src/playground/sidebar/sidebar-fixed.component.html
- src/playground/sidebar/sidebar-toggle.component.html
- src/playground/spinner/spinner-button.component.ts
- src/playground/spinner/spinner-card.component.ts
- src/playground/stepper/stepper-playground.component.scss
- src/playground/stepper/stepper-showcase.component.html
- src/playground/stepper/stepper-validation.component.html
- src/playground/stepper/stepper-vertical.component.html
> feat(playground): update examples to use the new `nbButton`

- package.json
> chore: fix ci:test script

- src/framework/theme/components/layout/layout.component.ts
- src/framework/theme/services/scroll.service.spec.ts
- src/framework/theme/services/scroll.service.ts
> refactor(layout): add ability to use default values in `scroll` method

- src/framework/theme/components/accordion/_accordion.component.theme.scss
- src/framework/theme/components/accordion/accordion-item.component.scss
- src/framework/theme/styles/themes/_default.scss
> fix(accordion): fix accordion border-radius and shadow

- docs/app/example/example.component.ts
> fix(docs): delay first calculation of height

- src/framework/theme/components/layout/layout.component.ts
> fix(docs): update copy

- src/framework/theme/components/button/button.component.scss
- src/framework/theme/components/button/button.component.ts
- src/framework/theme/components/button/button.spec.ts
- src/playground/button/button-full-width.component.html
- src/playground/button/button-full-width.component.ts
- src/playground/playground-routing.module.ts
- src/playground/playground.module.ts
> feat(button): add `fullWidth` mode

- src/framework/theme/styles/global/bootstrap/_bootstrap.theme.scss
- src/framework/theme/styles/global/bootstrap/_layout.scss
> override default bootstrap style for row css class

- package.json
> chore: fix release test script

- src/framework/theme/styles/global/bootstrap/_modals.scss
Fixes position of header elements in rtl mode.
Closes: #419.
> fix(modal): rtl modal header

- src/framework/theme/components/calendar/calendar.component.ts
> fix(calendar): range usage require NbCalendarRangeModule info fix#633

- docs/app/blocks/components/live-example-block/live-example-block.component.html
- docs/app/blocks/components/live-example-block/live-example-block.component.ts
- src/framework/theme/components/list/infinite-list.directive.ts
- src/framework/theme/services/ruler.service.ts
- src/framework/theme/services/scroll.service.ts
- src/playground/infinite-list/infinite-list-placeholders.component.ts
- src/playground/playground-routing.module.ts
- src/playground/playground.module.ts
> docs(infinite list): add example with placeholders on top

- src/framework/theme/components/sidebar/sidebar.component.scss
- src/framework/theme/components/sidebar/sidebar.component.ts
> Add ability fix sidebar container

- src/framework/theme/components/tabset/_tabset.component.theme.scss
- src/framework/theme/styles/themes/_corporate.scss
- src/framework/theme/styles/themes/_cosmic.scss
- src/framework/theme/styles/themes/_default.scss
> Update background fot tabset selected

- src/framework/auth/components/login/login.component.ts
- src/framework/auth/strategies/password/password-strategy-options.ts
- src/framework/auth/strategies/password/password-strategy.ts
> fix(login): take into account remember me setting

- docs/app/@theme/services/menu.service.ts
- docs/app/@theme/styles/themes.scss
- docs/app/blocks/components/components-overview-block/components-overview-block.component.html
- docs/app/blocks/components/components-overview-block/components-overview-block.component.scss
- docs/app/blocks/components/components-overview-block/components-overview-block.component.ts
- docs/app/documentation/documentation.component.scss
- docs/structure.ts
> feat(docs): add groups to components list

- docs/articles/install-into-existing.md
Angular 6 update documentation
> Angular 6 file is `angular.json`

- docs/articles/security-intro.md
> feat(docs): fix typo

- package-lock.json
- package.json
- src/framework/icons/package.json
> feat(icons): publish

- src/framework/auth/components/login/login.component.html
- src/framework/auth/components/register/register.component.html
- src/framework/auth/components/request-password/request-password.component.html
- src/framework/auth/components/reset-password/reset-password.component.html
> refactor(auth): change phrasing

- src/framework/bootstrap/styles/_hero-buttons.scss
- src/framework/theme/components/button/_button-heroes.scss
> fix(theme): use existing variable

- docs/app/@theme/components/hero/hero.component.scss
- docs/app/@theme/components/hero/hero.component.ts
> feat(docs): add star & download badges into the hero section

- docs/index.html
> chore(docs): add twitter pixes

- src/framework/theme/components/cdk/overlay/_overlay.theme.scss
> fix(theme): inline cdk styles

- CHANGELOG.md
- package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 2.0.1

- package.json
- scripts/publish.sh
> chore(release): add publish script

- src/framework/theme/components/checkbox/_checkbox.component.theme.scss
> fix(checkbox): hide check mark when unchecked and disabled

- docs/index.html
> chore: add reddit pixel to docs

- src/framework/theme/components/accordion/accordion-item-header.component.ts
- src/framework/theme/components/button/button.component.ts
> fix(nbButton): set disabled DOM property

- README.md
> chore: update readme with survey link

- src/framework/theme/components/sidebar/_sidebar.component.theme.scss
> fix(theme): fix sidebar shadow styles for Safari

- src/framework/theme/components/cdk/overlay/overlay-trigger.spec.ts
- src/framework/theme/components/cdk/overlay/overlay-trigger.ts
> fix(overlay): fix click trigger

- src/framework/auth/auth.module.ts
- src/framework/auth/index.ts
> fix(auth): don't import child routes as it will rewrite the app routes

- src/framework/theme/components/radio/radio.component.ts
> docs(radio): fix radio description typo

- src/framework/theme/components/tooltip/tooltip.directive.ts
> fix(theme): provide component factory resolver in tooltip

- src/framework/theme/components/sidebar/sidebar.component.ts
> fix(sidebar): expand if not compacted or collapsed

- src/framework/theme/components/cdk/overlay/overlay-container.ts
- src/framework/theme/components/window/window.component.ts
- src/framework/theme/components/window/window.service.spec.ts
> fix(window): reattach overlay after window expand

- src/framework/theme/components/popover/_popover.component.theme.scss
> fix(popover): inner triangle size

- src/framework/theme/components/button/_button-colors.scss
> fix(button): return text color on focus

- src/framework/theme/components/context-menu/context-menu.directive.ts
- src/framework/theme/components/datepicker/datepicker.component.ts
- src/framework/theme/components/datepicker/datepicker.spec.ts
- src/framework/theme/components/popover/popover.directive.ts
- src/framework/theme/components/tooltip/tooltip.directive.ts
> Overlay directives lazy overlay instantiation

- docs/articles/professional-services.md
> chore: update services page wordings

- src/framework/theme/components/input/input.directive.ts
- src/playground/input/input-form.component.ts
- src/playground/playground-routing.module.ts
- src/playground/playground.module.ts
- Input form binding example added
> docs(input): add 1 new example

- src/framework/theme/components/layout/layout.component.ts
> fix(layout): prevent dom api calls on server

- src/framework/theme/styles/global/_overrides.scss
> fix(theme): fix normalize import to not include file type extension

- src/app/playground-components.ts
- src/framework/theme/components/user/user.component.ts
- src/playground/with-layout/user/user-avatar-settings.component.html
- src/playground/with-layout/user/user-avatar-settings.component.ts
- src/playground/with-layout/user/user-hide-captions.component.html
- src/playground/with-layout/user/user-hide-captions.component.ts
- src/playground/with-layout/user/user-routing.module.ts
- src/playground/with-layout/user/user-showcase.component.html
- src/playground/with-layout/user/user-sizes.component.html
- src/playground/with-layout/user/user.module.ts
- Hide Captions In User Component example added
- Avatar Image Settings example added
- Xlarge size added in Multiple Sizes example
> docs(user): add 2 new examples, improve 1 existing example

- src/framework/theme/components/datepicker/datepicker.component.ts
Check overlay ref was created before detaching and disposing of it.
Closes #1083
> fix(theme): check ref before detaching

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 3.1.0 :christmas_tree:

- .github/ISSUE_TEMPLATE.md
- README.md
> docs: update readme with a link to StackBlitz

- src/framework/theme/components/cdk/overlay/overlay-trigger.spec.ts
- src/framework/theme/components/cdk/overlay/overlay-trigger.ts
- src/framework/theme/components/cdk/overlay/overlay.module.ts
- src/framework/theme/components/context-menu/context-menu.directive.ts
- src/framework/theme/components/datepicker/datepicker.component.ts
- src/framework/theme/components/popover/popover.directive.ts
- src/framework/theme/components/select/select.component.ts
- src/framework/theme/components/tooltip/tooltip.directive.ts
> refactor(overlay): trigger strategy builder is a service now

- DEV_DOCS.md
> docs(playground): add playground schematic description

- .gitattributes
Add .gitattributes file to set crossplatform lineendings
> chore: specify line endings

- src/framework/theme/components/route-tabset/route-tabset.component.ts
- src/playground/with-layout/tabset/route-tabset-showcase.component.ts
> fix(router-tabset): navigate using router link

- src/framework/theme/components/search/search.component.ts
Emit search activate and deactivate events when search opened from `NbSearchComponent`.
> fix(search): emit activate and deactivate events

- docs/articles/auth-azure.md
- docs/articles/auth-custom-ui.md
- docs/articles/auth-oauth2.md
> docs: fix github examples links

- src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay-handler.spec.ts
- src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay-handler.ts
- src/framework/theme/components/popover/popover.spec.ts
- src/framework/theme/components/tooltip/tooltip.component.ts
- src/framework/theme/components/tooltip/tooltip.directive.ts
- src/framework/theme/components/tooltip/tooltip.spec.ts
> feat(tooltip): dynamic inputs support

- src/framework/theme/schematics/collection.json
> refactor(schematics): make setup schematic public

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 3.2.1

- docs/app/@theme/components/footer/footer.component.html
> fix(docs): footer email link

- src/framework/auth/strategies/auth-strategy.ts
- src/framework/auth/strategies/password/password-strategy.spec.ts
> fix(auth): allow empty logout endpoint

- src/framework/security/security.options.ts
> fix(security): make config work with strict ts mode

- src/playground/with-layout/menu/menu-autocollapse.component.ts
Correcting the property name 'ulr' to 'url'
Correcting property name from 'ulr' to 'url'
> Correcting property name 'url'

- src/framework/theme/styles/_theming.scss
Added mixins for both `nb-for-theme` and `nb-except-for-theme` to work with multiple theme names with same content style
> feat(theme): multiple values for nb-(except-)for-theme

- docs/app/@theme/services/index.ts
- docs/app/@theme/services/metadata.service.ts
- docs/app/@theme/services/tabbed.service.ts
- docs/app/@theme/theme.module.ts
- docs/app/blocks/components/methods-block/methods-block.component.ts
- docs/app/blocks/components/props-block/props-block.component.ts
- package-lock.json
- package.json
> feat(docs): @docs-private support

- docs/articles/auth-strategy.md
> fix(docs): fix password strategy link

- package.json
> chore: fix release script to stop watching tests

- CHANGELOG.md
- package-lock.json
- package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 3.4.0

- docs/articles/auth-install.md
> docs(auth): add note on theming with portion of themes

- src/framework/theme/components/tree-grid/tree-grid.component.ts
> docs(tree-grid): add install instructions

- src/framework/theme/components/select/select.component.ts
- src/framework/theme/components/select/select.spec.ts
> fix(select): update selected after cd run is finished

- .travis.yml
- scripts/ci/travis-script.sh
Fixes diff on branches other than master.
Also adds 'next' branch to Travis build.
> chore: add next branch to travis

- .travis.yml
Will be enabled after updating tests to new colors, etc.
Disable e2e on next branch. Will be enabled after updating tests to new colors, etc.
> chore: disable e2e on next branch

- src/framework/theme/styles/_theming.scss
- src/framework/theme/styles/core/_breaking-notice.scss
> chore: add new theme system warning

- CHANGELOG.md
- package.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 3.4.2

- scripts/ci/travis-script.sh
> chore: fix pr diff

- src/framework/theme/styles/_theming.scss
- src/framework/theme/styles/core/_breaking-notice.scss
> fix: remove scss debug calls

- src/framework/theme/components/calendar-kit/services/native-date.service.spec.ts
- src/framework/theme/components/calendar-kit/services/native-date.service.ts
Closes #1332
Resolves the issue with date overflow while adding a month in native date service.
> fix(theme): native date service addMonth date overflow

- src/framework/theme/components/cdk/overlay/_overlay.theme.scss
- src/framework/theme/components/layout/layout.component.ts
> fix(cdk): fix scroll blocker for custom `withScroll` mode

- README.md
- docs/articles/auth-install.md
- docs/articles/bootstrap-integration.md
- docs/articles/install-into-existing.md
- docs/articles/security-install.md
> docs: specify particular 3rd version

- scripts/ci/travis-script.sh
> chore(ci): remove diff check for next branch

- src/framework/theme/components/calendar-kit/calendar-kit.module.ts
- src/framework/theme/components/calendar-kit/components/calendar-navigation/calendar-pageable-navigation.component.scss
- src/framework/theme/components/calendar-kit/components/calendar-navigation/calendar-pageable-navigation.component.spec.ts
- src/framework/theme/components/calendar-kit/components/calendar-navigation/calendar-pageable-navigation.component.ts
Use button with icons for months navigation.
Also fixes #1355.
> feat(calendar): use nb-icon in navigation buttons

- src/framework/theme/components/cdk/overlay/_overlay.theme.scss
- src/framework/theme/styles/themes/_default.scss
Theme property 'overlay-backdrop-bg' renamed to 'overlay-backdrop-background-color'.
> feat(overlay): Eva theme

- src/framework/theme/components/icon/_icon.component.theme.scss
- src/framework/theme/components/icon/icon.component.ts
- src/framework/theme/styles/themes/_default.scss
NbIconComponent status static fields removed.
STATUS_PRIMARY, STATUS_INFO, STATUS_SUCCESS, STATUS_WARNING, STATUS_DANGER.
'status' field now uses common NbComponentStatus type.
NbIconComponent static class names renamed to 'status-[status-name]'.
Following theme properties were renamed:
icon-primary-fg -> icon-primary-color
icon-info-fg -> icon-info-color
icon-success-fg -> icon-success-color
icon-warning-fg -> icon-warning-color
icon-danger-fg -> icon-danger-color
> feat(icon): Eva theme

- src/framework/theme/components/select/option.component.ts
- src/framework/theme/components/select/select.spec.ts
> fix(select): prevent navigation to disabled option from keyboard

- src/framework/theme/components/layout/layout.component.ts
> docs(layout): update theme properties list

- docs/app/@theme/components/footer/footer.component.scss
- docs/app/@theme/components/header/header.component.scss
- docs/app/@theme/styles/_common.scss
- docs/app/@theme/styles/themes.scss
- docs/app/blocks/components/components-overview-block/components-overview-block.component.html
- docs/app/blocks/components/components-overview-block/components-overview-block.component.scss
- docs/app/documentation/documentation.component.scss
- docs/app/documentation/page/page.component.html
- docs/app/documentation/page/page.component.scss
- docs/app/documentation/page/page.component.ts
- src/framework/theme/components/calendar/_calendar.component.theme.scss
- src/framework/theme/components/layout/_layout.component.theme.scss
- src/framework/theme/components/layout/layout.component.ts
- src/framework/theme/components/menu/_menu.component.theme.scss
- src/framework/theme/components/sidebar/_sidebar.component.theme.scss
- src/framework/theme/styles/global/typography/_typography.scss
- src/framework/theme/styles/themes/_default.scss
> feat(docs): Eva update

- .travis.yml
> build: enable publish and deploy

- src/framework/theme/components/popover/popover.directive.ts
- src/framework/theme/components/select/select.component.ts
> feat: remove fields scheduled to be removed in 4.0

- scripts/ci/travis-script.sh
> build: enable diff check

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.0.0-rc.1

- docs/app/documentation/page/page.component.ts
> fix(docs): trigger change detection after if tab updated

- docs/assets/ghspa.js
> feat(docs): add redirect to 'next' subdirectory

- docs/app/documentation/page/page.component.html
> fix(docs): use current tab component property

- docs/app/blocks/components/components-overview-block/components-overview-block.component.html
- docs/app/blocks/components/components-overview-block/components-overview-block.component.scss
- src/framework/theme/components/button/button.component.ts
- src/framework/theme/components/chat/chat.component.ts
- src/framework/theme/components/search/_search.component.theme.scss
- src/framework/theme/components/search/search.component.ts
- src/framework/theme/components/tree-grid/data-source/tree-grid-filter.service.ts
- src/playground/with-layout/calendar/calendar-bounding-month.component.ts
- src/playground/with-layout/calendar/calendar-custom-day-cell-showcase.component.ts
- src/playground/with-layout/calendar/calendar-filter.component.ts
- src/playground/with-layout/calendar/calendar-min-max.component.ts
- src/playground/with-layout/calendar/calendar-range-showcase.component.ts
- src/playground/with-layout/calendar/calendar-showcase.component.ts
- src/playground/with-layout/calendar/calendar-size.component.ts
- src/playground/with-layout/calendar/calendar-start-view.component.ts
- src/playground/with-layout/calendar/calendar-without-header.component.ts
- src/playground/with-layout/checkbox/checkbox-indeterminate.component.ts
- src/playground/with-layout/checkbox/checkbox.module.ts
- src/playground/with-layout/dialog/dialog-result.component.ts
- src/playground/with-layout/infinite-list/components/news-post.component.ts
- src/playground/with-layout/infinite-list/news-post-placeholder.component.scss
- src/playground/with-layout/menu/menu-service-children.ts
- src/playground/with-layout/menu/menu-service.component.ts
Mostly consists of typography fixes
> fix(docs): update examples after Eva migration

- scripts/gulp/tasks/bundle/bundle.ts
- scripts/gulp/tasks/bundle/rollup-config.ts
> build: generate eva-icons umd package

- README.md
- docs/articles/bootstrap-integration.md
- docs/articles/install-into-existing.md
- src/framework/theme/components/icon/icon.component.ts
> docs: specify next version in install instructions

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.0.0-rc.2

- src/framework/theme/styles/themes/_default.scss
Removes shadow from `tabset` and `route-tabset`
> refactor(tabset): remove shadow

- src/playground/with-layout/popover/popover-modes.component.html
- src/playground/with-layout/popover/popover-test.component.ts
> docs(popover): use new trigger input name

- src/framework/theme/components/datepicker/_datepicker-container.component.theme.scss
- src/framework/theme/components/datepicker/datepicker.directive.ts
- src/framework/theme/styles/themes/_default.scss
> refactor(datepicker): remove primary border

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> chore: bump version to rc.3

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.0.0-rc.4

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.0.0-rc.5

- src/framework/theme/components/checkbox/checkbox.component.ts
- src/framework/theme/components/checkbox/checkbox.spec.ts
> fix(checkbox): fix value output

- package.json
> chore: make main package.json private and enable e2e on release

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: v4.0.0-rc.7

- docs/app/@theme/styles/themes.scss
> fix(docs): fix transparent background color

- src/framework/theme/styles/themes/_mapping.scss
> fix(theme): fix accordion mapping with incorrect font maps

- src/framework/theme/schematics/ng-add/index.spec.ts
- src/framework/theme/schematics/ng-add/register-theme/theme-content.ts
- src/framework/theme/schematics/ng-add/schema.json
- src/framework/theme/schematics/ng-add/schema.ts
> feat(schematics): add dark theme

- angular.json
- docs/app/@theme/styles/pace.theme.scss
- docs/app/@theme/styles/styles.scss
- package-lock.json
- package.json
Add [pace-js](http://github.hubspot.com/pace/) lib to show routing loader.
> feat(docs): add routing loader

- docs/app/@theme/styles/_common.scss
> fix(docs): disable custom outline as it breaks Eva components

- .travis.yml
> chore: disable angular analytics prompt on ci

- src/assets/data/news.json
Fixes infinite list example when running playground directly.
Closes #1532.
> chore(playground): add missing infinite list assets

- src/framework/bootstrap/styles/_button-group.scss
- src/framework/bootstrap/styles/_default-form-control.scss
- src/framework/bootstrap/styles/_globals.scss
- src/framework/bootstrap/styles/_icon-buttons.scss
- src/framework/bootstrap/styles/_modals.scss
- src/framework/bootstrap/styles/_outline-buttons.scss
- src/framework/bootstrap/styles/_status-buttons.scss
- src/playground/without-styles/bootstrap/bootstrap-test.component.html
- src/playground/without-styles/bootstrap/bootstrap-test.component.ts
- src/playground/without-styles/bootstrap/bootstrap.module.ts
> fix(bootstrap): button group, modal and input

- src/framework/theme/components/radio/_radio.component.theme.scss
- src/framework/theme/components/radio/radio.component.scss
- src/framework/theme/components/radio/radio.component.ts
Looks fine on almost all default zoom modes. 110% still distorts inner circle.
> fix(radio): prevent circles distraction

- e2e/layout-theme.e2e-spec.ts
- src/framework/theme/components/radio/_radio.component.theme.scss
- src/framework/theme/styles/themes/_dark.scss
- src/framework/theme/styles/themes/_default.scss
- src/framework/theme/styles/themes/_mapping.scss
> refactor(theme): Eva sync

- docs/app/blocks/components/components-overview-block/components-overview-block.component.scss
- src/playground/styles/example-helpers.scss
- src/playground/with-layout/alert/alert-accents.component.html
- src/playground/with-layout/alert/alert-colors.component.html
- src/playground/with-layout/alert/alert-outline.component.html
- src/playground/with-layout/alert/alert-showcase.component.html
- src/playground/with-layout/alert/alert-sizes.component.html
- src/playground/with-layout/button/button-colors.component.html
- src/playground/with-layout/button/button-full-width.component.html
- src/playground/with-layout/button/button-hero.component.html
- src/playground/with-layout/button/button-icon.component.html
- src/playground/with-layout/button/button-outline.component.html
- src/playground/with-layout/button/button-shapes.component.html
- src/playground/with-layout/button/button-showcase.component.html
- src/playground/with-layout/button/button-sizes.component.html
- src/playground/with-layout/button/button-types.component.html
- src/playground/with-layout/button/button-types.component.ts
- src/playground/with-layout/icon/icon-colors.component.html
- src/playground/with-layout/icon/icon-showcase.component.html
- src/playground/with-layout/input/input-showcase.component.ts
- src/playground/with-layout/progress-bar/progress-bar-interactive.component.html
- src/playground/with-layout/spinner/spinner-button.component.ts
- src/playground/with-layout/toastr/toastr-destroy-by-click.component.ts
- src/playground/with-layout/toastr/toastr-duration.component.ts
- src/playground/with-layout/toastr/toastr-icon.component.ts
- src/playground/with-layout/toastr/toastr-positions.component.ts
- src/playground/with-layout/toastr/toastr-prevent-duplicates.component.ts
- src/playground/with-layout/toastr/toastr-showcase.component.ts
- src/playground/with-layout/toastr/toastr-statuses.component.ts
> fix(docs): example row helper

- docs/app/@theme/components/icon-card/icon-card.component.scss
- docs/app/blocks/components/theme-block/theme-block.component.scss
- docs/app/home/home.component.html
- docs/app/home/home.component.scss
> fix(docs): change features section background

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: v4.0.0-rc.8

- src/framework/theme/styles/themes/_mapping.scss
> fix(smart table): map to existing theme variable

- docs/assets/ghspa.js
> chore(docs): add 3.5.0 redirect

- docs/app/@theme/components/eva/eva.components.scss
- docs/app/blocks/components/live-example-block/live-example-block.component.scss
- docs/app/home/home.component.scss
> fix(docs): remove concave line and update dark example background

- CONTRIBUTING.md
> docs: fix CONTRIBUTING.md typo

- README.md
> chore: temporary hide un-updated demos from readme

- docs/app/@theme/styles/themes.scss
> fix(docs): use primary color for highlight

- .travis.yml
- scripts/ci/browserstack/stop-tunnel.sh
- scripts/ci/travis-script.sh
> feat: enable ci for 3.6.0 branch

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: v3.6.0

- DEV_DOCS.md
> chore(dev docs): add toc and update release steps

- DEV_DOCS.md
> chore(dev docs): specify correct lts tag

- CHANGELOG.md
> chore: add 3.6.0 release to changelog

- docs/assets/ghspa.js
> chore(docs): add 3.6.0 redirect

- src/framework/theme/components/layout/layout.component.scss
> fix(layout): set top position on fixed header

- src/framework/theme/components/layout/_layout.component.theme.scss
> fix(sidebar): prevent translation to the top when overlay opened

- docs/app/@theme/components/header/header.component.scss
- docs/app/@theme/components/header/header.component.ts
- docs/app/@theme/components/search/search.component.scss
- docs/app/@theme/components/search/search.component.ts
- docs/app/@theme/services/version.service.ts
- docs/app/@theme/styles/styles.scss
- docs/app/@theme/styles/themes.scss
- docs/app/@theme/theme.module.ts
- docs/assets/ghspa.js
> feat(docs): add version select

- docs/articles/getting-started/what-is-nebular.md
> fix(docs): typo fix

- src/framework/bootstrap/README.md
- src/framework/eva-icons/README.md
> fix(docs): fix incorrect eva-icons/bootstrap readme

- src/framework/theme/styles/_theming.scss
It follows https://github.com/akveo/nebular/pull/1506 to fix deprecation warnings of dart-sass 2.0.
> fix(theme): deprecation warning of dart sass 2.0.0

- DEV_DOCS.md
- angular.json
- docs/app/@theme/components/header/header.component.ts
- docs/app/@theme/services/version.service.ts
- docs/app/documentation/page/page.component.scss
- docs/environments/environment.prod.ts
- docs/environments/environment.ts
- docs/versions.json
> refactor(docs): read versions from config

- angular.json
- docs/app/@theme/components/header/header.component.scss
- docs/app/@theme/components/header/header.component.ts
- docs/app/@theme/services/version.service.ts
- docs/app/@theme/styles/_common.scss
- docs/app/@theme/styles/styles.scss
- docs/app/@theme/styles/themes.scss
- docs/app/@theme/theme.module.ts
- docs/assets/ghspa.js
- docs/environments/environment.prod.ts
- docs/environments/environment.ts
- docs/versions.json
> feat(docs): add version switcher

- CHANGELOG.md
- docs/assets/ghspa.js
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 3.6.1

- CHANGELOG.md
> chore: add 3.6.1 release notes

- CHANGELOG.md
- docs/assets/ghspa.js
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.1.0

- src/framework/theme/components/menu/_menu.component.theme.scss
- src/framework/theme/styles/themes/_mapping.scss
> fix(menu): icon color should use `text-hint-color`

- src/app/playground-components.ts
- src/framework/theme/components/toastr/toastr-config.ts
- src/framework/theme/components/toastr/toastr.service.spec.ts
- src/framework/theme/components/toastr/toastr.service.ts
- src/playground/with-layout/toastr/toastr-prevent-duplicates-behaviour.component.ts
- src/playground/with-layout/toastr/toastr-routing.module.ts
- src/playground/with-layout/toastr/toastr.module.ts
Adds toaster service duplication behaviour
> feat(toastr): add duplicates behavior

- src/app/playground-components.ts
- src/framework/theme/components/toastr/toastr-config.ts
- src/framework/theme/components/toastr/toastr.service.spec.ts
- src/framework/theme/components/toastr/toastr.service.ts
- src/playground/with-layout/toastr/toastr-limit.component.ts
- src/playground/with-layout/toastr/toastr-routing.module.ts
- src/playground/with-layout/toastr/toastr.module.ts
Adds the possibility to limit visible toasts.
> feat(toastr): add toasts limit

- package-lock.json
- package.json
Fixes webdriver-manager error with chromedriver version when running e2e locally.
> chore: update protractor

- angular.json
- e2e/select.e2e-spec.ts
- src/app/playground-components.ts
- src/framework/theme/components/select/_select.component.theme.scss
- src/framework/theme/components/select/select.component.ts
- src/framework/theme/components/select/select.spec.ts
- src/playground/with-layout/select/select-routing.module.ts
- src/playground/with-layout/select/select-test.component.ts
- src/playground/with-layout/select/select.module.ts
> fix(select): prevent empty select height collapsing

- src/framework/theme/components/icon/_icon.component.theme.scss
- src/framework/theme/styles/themes/_mapping.scss
Prevents icon vertical align override when used with Bootstrap.
> fix(icon): specify vertical align

- src/framework/theme/components/select/_select-outline.scss
- src/framework/theme/components/select/_select.component.theme.scss
- src/framework/theme/components/select/select.component.ts
>  fix(select): remove usage of deleted variables

- src/framework/auth/components/login/login.component.html
- src/framework/auth/components/register/register.component.html
> style(auth): fix two minor typos in auth components

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.1.1

- src/framework/auth/public_api.ts
> fix(auth): include helpers into public api

- README.md
> chore: add Stackblitz template to readme

- src/framework/theme/components/menu/menu.service.ts
- src/framework/theme/components/menu/menu.spec.ts
Described in https://github.com/akveo/nebular/pull/1660#discussion_r298809662
> fix(menu): path fragment comparison

- docs/articles/guides/custom-icons.md
- docs/structure.ts
- src/framework/theme/components/icon/icon.component.ts
> docs(icons): docs on how to add custom icon pack

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.1.2

- docs/articles/guides/custom-icons.md
- src/framework/theme/components/icon/icon.component.ts
> docs(icon): add module import to docs

- CHANGELOG.md
- docs/assets/ghspa.js
- docs/versions.json
Update changelog and versions config for the docs app
> chore(docs): update lts version to 3.6.2

- docs/articles/guides/install.md
> fix(docs): custom theme link

- src/framework/theme/components/select/select.component.html
> fix(select): remove max width from options list in full width select

- src/framework/theme/components/accordion/_accordion.component.theme.scss
- src/framework/theme/components/accordion/accordion-item-header.component.ts
> fix(accordion): prevent styling of projected icons

- src/framework/theme/components/checkbox/checkbox.component.ts
- src/framework/theme/components/checkbox/checkbox.spec.ts
> fix(checkbox): prevent second click event from input

- src/framework/theme/components/dialog/dialog.service.ts
> fix(dialog): stop listening for close events when dialog closes

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.1.3

- packages-smoke/package-lock.json
- packages-smoke/package.json
Fixes error with Chrome version when starting e2e tests
> fix(packages smoke): update webdriver-manager

- src/framework/theme/components/cdk/overlay/overlay-position.spec.ts
- src/framework/theme/components/cdk/overlay/overlay-position.ts
> fix(popover): add missing start and end positions to positions mapping

- docs/articles/auth/install.md
- src/framework/auth/styles/_all.scss
> docs(auth): remove outdated paragraph

- docs/app/@theme/services/version.service.ts
> fix(version service): use updated version json scheme

- src/framework/theme/components/toggle/toggle.component.ts
> docs(toggle): update description

- packages-smoke/package-lock.json
- packages-smoke/package.json
Fixes error with chrome driver
> fix(packages smoke): update webdriver manager

- src/framework/theme/components/list/list-pager.directive.spec.ts
Fixes failing page tracker tests
> test(list pager): increase default spy wait time

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.2.0

- scripts/ci/deploy-docs.sh
- scripts/ci/travis-script.sh
> fix(ci): prevent travis from killing deploy docs job

- src/framework/theme/components/select/select.component.ts
- src/framework/theme/components/select/select.spec.ts
> fix(select): allow initial falsy values

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.2.1

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.2.2

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.3.0

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.3.1

- docs/articles/auth/custom-ui.md
> chore(docs): fix auth example dead link

- README.md
> chore: update stackblitz link

- src/framework/theme/components/layout/_layout.component.theme.scss
> fix(layout header): prevent stretching wider than window max width

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.4.0

- docs/articles/guides/custom-icons.md
> docs(eva icons): add eva-icons package to install command

- docs/app/home/home.component.ts
> chore(docs): fix typo

- package.json
> chore: execute lint tasks in parallel

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.5.0

- docs/app/@theme/components/search/search.component.scss
> chore(docs): use correct theme variable

- src/framework/theme/components/cdk/overlay/overlay-trigger.ts
> fix(hover trigger strategy): prevent resubscription after destroy

- src/framework/theme/components/context-menu/context-menu.directive.ts
- src/framework/theme/components/context-menu/context-menu.spec.ts
- src/framework/theme/components/dialog/dialog-config.ts
- src/framework/theme/components/dialog/dialog.service.spec.ts
- src/framework/theme/components/dialog/dialog.service.ts
- src/framework/theme/components/toastr/toast.component.ts
- src/framework/theme/components/toastr/toastr-config.ts
- src/framework/theme/components/toastr/toastr.service.spec.ts
> feat: add custom css class on overlays

- src/framework/theme/components/toggle/_toggle.component.theme.scss
- src/framework/theme/components/toggle/toggle.component.ts
- src/framework/theme/components/toggle/toggle.spec.ts
Closes https://github.com/akveo/nebular/issues/1976
> fix(toggle): animation for IE11

- docs/articles/guides/install.md
> fix(docs): update links inside install guide page

- src/framework/theme/components/select/option.component.ts
- src/framework/theme/components/select/select.component.ts
- src/framework/theme/components/select/select.spec.ts
Fixes #1921.
Also probably related to #1336.
> fix(select): set value from queue when options change

- docs/app/app.routes.ts
- docs/app/example/example-routing.module.ts
- docs/tsconfig.app.json
- schematics/playground-components/index.ts
- schematics/playground-module/add-to-modules.ts
- schematics/utils/path.ts
- schematics/utils/routing.ts
- src/app/app.module.ts
- src/framework/date-fns/date-fns.module.ts
- src/framework/theme/components/cdk/adapter/block-scroll-strategy-adapter.ts
- src/framework/theme/components/cdk/overlay/overlay-container.ts
- src/framework/theme/components/cdk/overlay/overlay.module.ts
- src/framework/theme/components/datepicker/datepicker.component.ts
- src/framework/theme/components/datepicker/datepicker.module.ts
- src/framework/theme/components/dialog/dialog.module.ts
- src/framework/theme/components/tree-grid/tree-grid.component.spec.ts
- src/playground/playground-routing.module.ts
- src/playground/with-layout/with-layout-routing.module.ts
- src/playground/without-layout/smart-home/app-routing.module.ts
- src/playground/without-layout/without-layout-routing.module.ts
- src/playground/without-styles/without-styles-routing.module.ts
- src/tsconfig.app.json
- src/tsconfig.wp.json
> feat: Ivy compatibility

- src/framework/theme/components/radio/_radio.component.theme.scss
- src/framework/theme/components/radio/radio.component.scss
> fix(radio): reverse order of elements in RTL

- src/framework/theme/components/toggle/toggle.component.ts
> fix(toggle): set correct ARIA role

- scripts/gulp/tasks/bump-versions.ts
> chore: fix bump version script to work with gulp 4

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 4.6.0

- docs/app/@theme/components/eva/eva.component.html
- docs/app/@theme/components/eva/eva.components.scss
> chore(docs): add Eva black friday deal

- docs/versions.json
> chore(docs): set Eva deal commit as current docs version

- docs/app/@theme/components/eva/eva.component.html
> chore(docs): change Eva deal to Cyber Monday

- docs/versions.json
> chore(docs): update docs checkout target

- docs/app/@theme/components/eva/eva.component.html
- docs/app/@theme/components/eva/eva.components.scss
- docs/versions.json
> chore: remove deals text from docs

- src/framework/theme/public_api.ts
> fix: add scroll strategy options to public api

- src/framework/theme/components/button/_button.component.theme.scss
- src/framework/theme/components/button/button.component.scss
- src/framework/theme/components/button/button.component.ts
- src/framework/theme/components/radio/radio.component.scss
- src/framework/theme/components/toggle/_toggle.component.theme.scss
- src/framework/theme/components/toggle/toggle.component.scss
- src/framework/theme/components/toggle/toggle.component.ts
- src/framework/theme/styles/themes/_mapping.scss
> refactor: sync sizes with Eva 1.3

- docs/versions.json
> chore(docs): include 5-beta.1 version

- src/framework/theme/components/cdk/overlay/overlay-trigger.ts
> fix(trigger): prevent stream destroy on mouse leave

- src/framework/theme/components/context-menu/_context-menu.component.theme.scss
- src/framework/theme/components/context-menu/context-menu.component.ts
- src/framework/theme/styles/themes/_mapping.scss
> refactor(context menu): extract text alignment to theme property

- src/framework/theme/components/button/_button-ghost.scss
- src/framework/theme/components/button/_button-outline.scss
- src/framework/theme/components/button/button.component.ts
- src/framework/theme/components/checkbox/_checkbox.component.theme.scss
- src/framework/theme/components/checkbox/checkbox.component.ts
- src/framework/theme/styles/core/_mixins.scss
- src/framework/theme/styles/themes/_mapping.scss
Allows to remove or override shadow via custom theme
> refactor: move focus inset shadow to theme

- src/framework/theme/styles/global/typography/_typography.scss
> fix(typography): concat anchor selector with color class

- src/framework/theme/styles/global/typography/_typography.scss
- src/framework/theme/styles/themes/_mapping.scss
> feat(typography): add anchor text decoration theme property

- docs/app/documentation/documentation.component.html
> chore(docs): replace email with SO and GitHub links

- docs/app/@theme/styles/styles.scss
> chore(docs): include options list theme into docs theme

- docs/versions.json
> chore(docs): include 5.0.0-beta.2

- src/framework/theme/components/cdk/overlay/overlay-trigger.ts
> fix(focus trigger): prevent stream destroy on focus out

- docs/versions.json
> chore(docs): update next docs to 5.0.0-beta.3

- src/framework/theme/styles/global/typography/_typography.scss
> fix(typography): use text theme vars for text color classes

- src/framework/theme/components/form-field/form-field.component.html
- src/framework/theme/components/form-field/form-field.component.scss
> fix(form field): make form control container take all space

- docs/versions.json
> refactor: update docs versions

- src/framework/theme/components/input/input.directive.ts
> fix(input): use correct status property name

- src/framework/theme/components/cdk/overlay/overlay-position.spec.ts
- src/framework/theme/components/layout/layout.component.ts
> fix(layout): access view child property after view init

- src/framework/theme/components/button/button.component.scss
- src/framework/theme/components/button/button.component.ts
- src/framework/theme/components/checkbox/checkbox.component.scss
- src/framework/theme/components/checkbox/checkbox.component.ts
- src/framework/theme/components/form-field/_form-field.component.theme.scss
- src/framework/theme/components/form-field/form-field.component.html
- src/framework/theme/components/form-field/form-field.component.scss
- src/framework/theme/components/form-field/form-field.component.ts
- src/framework/theme/components/input/_input.directive.theme.scss
- src/framework/theme/components/input/input.directive.ts
- src/framework/theme/components/option/option.component.scss
- src/framework/theme/components/option/option.component.ts
- src/framework/theme/components/select/select.component.scss
- src/framework/theme/components/select/select.component.ts
- src/framework/theme/components/select/select.spec.ts
- src/framework/theme/components/toggle/toggle.component.scss
- src/framework/theme/components/toggle/toggle.component.ts
> fix(theme): prevent transition to initial status

- src/framework/theme/components/calendar/_calendar.component.theme.scss
> chore(calendar): extract calc terms into scss vars

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 5.0.0

- src/framework/theme/components/cdk/overlay/overlay-position.ts
- src/framework/theme/components/popover/popover.directive.ts
- src/framework/theme/components/tooltip/tooltip.directive.ts
> fix(popover, tooltip): template check hint for adjustment

- README.md
The browser support details were supposed to be a table but they were not formatted properly to display a markdown table
> fix(readme): fix browser support table

- docs/versions.json
> chore(docs): include banner into current version docs

- docs/app/@theme/components/hubspot-cta/akveo-services-banner.component.scss
- docs/app/@theme/components/hubspot-cta/akveo-services-banner.component.ts
Fixes styles of akveo services banner (move a bit left)
> chore(docs): fix akveo services banner alignment

- docs/app/documentation/page/page.component.scss
- docs/articles/auth/backend-api.md
- docs/articles/getting-started/what-is-nebular.md
> docs: update bundle links

- src/framework/auth/styles/prebuilt/corporate.scss
- src/framework/auth/styles/prebuilt/dark.scss
fix theme mismatch of dark and corporate of auth module
> fix(auth): set correct theme for auth

- docs/articles/auth/firebase-authentication.md
> docs(firebase-auth): use correct sponsors links

- docs/versions.json
> chore(docs): change current docs checkout target

- src/framework/theme/components/datepicker/_datepicker-container.component.theme.scss
- src/framework/theme/styles/themes/_mapping.scss
> fix(datepicker): background and border theming

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 6.0.1

- README.md
- docs/app/@theme/components/eva/eva.component.html
- docs/app/@theme/components/footer/footer.component.html
- docs/app/@theme/components/hero/hero.component.ts
- docs/articles/auth/backend-api.md
- docs/articles/design-system/custom-theme.md
- docs/articles/design-system/enable-customizable-theme.md
- docs/articles/design-system/intro.md
- docs/articles/design-system/typography.md
- docs/articles/getting-started/professional-services.md
- docs/articles/getting-started/what-is-nebular.md
- docs/articles/migration/350-400.md
Revert short links to long ones back
> chore(links): revert hubspot links to long ones back again

- .travis.yml
> chore(ci): up node version

- docs/versions.json
> chore(docs): change current docs version

- src/framework/theme/public_api.ts
> chore(build): remove duplicate export

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 6.1.0

- package.json
- scripts/gulp/tasks/build/bundle/bundle.ts
- scripts/gulp/tasks/build/compile/ts-configs.ts
- scripts/gulp/tasks/build/compile/typescript.ts
- scripts/gulp/tasks/config.ts
> fix(build): provide ES5 code in UMD bundles

- docs/articles/auth/firebase-authentication.md
> docs(firebase-auth): correct typo in install instruction

- src/framework/theme/components/datepicker/datepicker.module.ts
- src/framework/theme/components/timepicker/timepicker.directive.ts
Closes #2524. And small timepicker docs fix (Closes #2526).
> feat(datepicker): export calendar with time component

- src/framework/theme/components/datepicker/datepicker.module.ts
- src/framework/theme/components/timepicker/timepicker.module.ts
And also remove unnecessary modules imports.
Closes #2527. Closes #2525.
> fix(timepicker): remove duplicate providers

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 6.2.0

- README.md
> chore(readme): add template links

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 6.2.1

- docs/articles/auth/firebase-authentication.md
Tiny typo on firebase auth article
> chore(docs): fix typo in package name

- src/framework/theme/components/icon/icon.component.ts
> docs(icon): add required to install package 

- src/framework/theme/components/toastr/toastr-config.ts
- src/framework/theme/components/toastr/toastr.service.ts
> docs(toastr): correct typo

- docs/articles/guides/custom-icons.md
> docs(icon): correct typo in a property name

- src/framework/theme/components/datepicker/datepicker.directive.ts
> docs(timepicker): add closing tag bracket

- src/framework/theme/components/cdk/overlay/overlay-container.ts
- src/framework/theme/components/cdk/overlay/overlay.module.ts
- src/framework/theme/components/context-menu/context-menu.component.ts
- src/framework/theme/components/datepicker/datepicker-container.component.ts
- src/framework/theme/components/popover/popover.component.ts
`NbPositionedContainer` renamed to `NbPositionedContainerComponent`.
> feat(overlay): add missing component class suffix

- src/framework/auth/styles/_all.scss
- src/framework/auth/styles/prebuilt/corporate.scss
- src/framework/auth/styles/prebuilt/cosmic.scss
- src/framework/auth/styles/prebuilt/dark.scss
- src/framework/auth/styles/prebuilt/default.scss
Replace `~@nebular/auth/styles/all` with `~@nebular/auth/styles/globals`.
> feat(auth): remove redundant _all.scss theme file

- src/framework/theme/components/option/option-group.component.ts
- src/framework/theme/components/option/option.component.ts
- src/framework/theme/components/radio/radio-group.component.ts
- src/framework/theme/components/select/select.component.ts
> fix(radio, select): prevent updates of destroyed component

- src/framework/theme/components/autocomplete/autocomplete.directive.ts
- src/framework/theme/components/datepicker/datepicker.component.ts
- src/framework/theme/components/select/select.component.ts
- src/framework/theme/components/tooltip/tooltip.directive.ts
> feat: add ability to customize overlay offset

- src/framework/theme/components/sidebar/sidebar.component.ts
> fix(sidebar): emit state change

- src/framework/theme/components/sidebar/sidebar.component.ts
Added change detector ref constructor parameter.
> refactor(sidebar): use OnPush change detection strategy

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 7.0.0

- src/framework/theme/components/button/_button-filled.scss
- src/framework/theme/components/button/_button-ghost.scss
- src/framework/theme/components/button/_button-hero.scss
- src/framework/theme/components/button/_button-outline.scss
- src/framework/theme/components/button/_button.component.theme.scss
> fix(button): styling for disabled anchor

- docs/app/@theme/components/hero/download-dialog.component.scss
- docs/app/@theme/components/hero/download-dialog.component.ts
- docs/app/@theme/components/hero/hero.component.scss
- docs/app/@theme/components/hero/hero.component.ts
- docs/app/@theme/components/index.ts
- docs/app/@theme/styles/hs-form.scss
- docs/app/@theme/styles/styles.scss
- docs/app/@theme/theme.module.ts
- docs/app/app.module.ts
- docs/index.html
> chore(docs): add download email form

- docs/versions.json
> chore(docs): update checkout targets for 6 and 7 versions

- docs/versions.json
> chore(docs): add for business section to current docs

- src/framework/theme/components/radio/radio-group.component.ts
- src/framework/theme/components/radio/radio.spec.ts
- src/playground/with-layout/radio/radio-disabled-group.component.ts
- src/playground/with-layout/radio/radio.module.ts
> fix(radio): add setDisabledState hook

- src/framework/theme/components/sidebar/sidebar.service.ts
- src/framework/theme/components/sidebar/sidebar.spec.ts
Fix getting sidebar state that was root cause of an error : connectable.connect() not function
Closes #2698
> fix(sidebar): sidebar state observable

- src/framework/theme/components/cdk/adapter/scroll-dispatcher-adapter.ts
> fix(scroll dispatcher): emit scroll events from cdkScrollable directive

- src/framework/theme/components/list/infinite-list.directive.ts
- src/framework/theme/components/tree-grid/data-source/tree-grid-data-source.ts
- src/framework/theme/services/ruler.service.ts
- src/framework/theme/services/scroll.service.ts
> chore: fix tslint warnings

- docs/app/@theme/components/components-promo/components-promo.component.scss
- docs/app/@theme/components/components-promo/components-promo.component.ts
- docs/app/@theme/components/eva/eva.component.html
- docs/app/@theme/components/for-business/for-business.component.ts
- docs/app/@theme/components/hero/hero.component.scss
- docs/app/@theme/components/hero/hero.component.ts
- docs/app/@theme/components/index.ts
- docs/app/@theme/theme.module.ts
- docs/app/home/home.component.html
- docs/app/home/home.component.scss
- docs/app/home/home.component.ts
> docs: update hero and add components promo

- src/app/playground-components.ts
- src/framework/theme/components/button-group/button-group.component.ts
- src/framework/theme/components/button-group/button-group.spec.ts
- src/framework/theme/components/button-group/button-toggle.directive.ts
- src/playground/with-layout/button-group/button-group-routing.module.ts
- src/playground/with-layout/button-group/button-group-value-change.component.html
- src/playground/with-layout/button-group/button-group-value-change.component.scss
- src/playground/with-layout/button-group/button-group-value-change.component.ts
- src/playground/with-layout/button-group/button-group.module.ts
> feat(button group): add valueChange output

- src/framework/theme/components/tag/tag.spec.ts
New unit test for NbTagComponent
> test(tag): add test for tag component

- src/framework/theme/components/tabset/tabset.component.spec.ts
- src/framework/theme/components/tabset/tabset.component.ts
added tab unique id Fixes #2727
> feat(tabset): add a tabId data attribute to the tab button

- src/framework/theme/components/tag/tag-list.component.ts
> fix(tag list): prevent autofocus on initial load

- src/app/playground-components.ts
- src/framework/theme/components/radio/radio-group.component.ts
- src/playground/with-layout/radio/radio-form.component.html
- src/playground/with-layout/radio/radio-form.component.ts
- src/playground/with-layout/radio/radio-routing.module.ts
- src/playground/with-layout/radio/radio-selected-option.pipe.ts
- src/playground/with-layout/radio/radio.module.ts
> docs(radio group): add forms example

- src/app/playground-components.ts
- src/framework/theme/components/route-tabset/route-tabset.component.ts
- src/playground/with-layout/tabset/components/route-tabset-children.component.ts
- src/playground/with-layout/tabset/route-tabset-showcase.component.ts
- src/playground/with-layout/tabset/tabset-routing.module.ts
- src/playground/with-layout/tabset/tabset.module.ts
> feat(route tabset): add support for NavigationExtras options

- src/framework/theme/components/chat/chat-form.component.ts
> fix(chat): double image preview

- src/framework/theme/components/button-group/button-group.spec.ts
Fixes failing button group tests.
> test(button group): take into account new timer from debounce

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 8.0.0

- src/framework/auth/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
> chore(release): update package versions

- README.md
> chore: update readme banner

- README.md
> chore: update readme bakery banner text

- README.md
> chore: update readme bakery banner link

- docs/versions.json
> chore(docs): update checkout target for 8 version

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 7.0.1

- src/framework/theme/components/checkbox/_checkbox.component.theme.scss
- src/framework/theme/components/checkbox/checkbox.component.ts
Closes #2270 
Fixed `nb-icon` styles in `NbCheckboxComponent`.
> fix(checkbox): don't style user icons in checkbox

- src/app/playground-components.ts
- src/framework/theme/components/datepicker/datepicker.directive.ts
- src/playground/with-layout/datepicker/datepicker-filter.component.ts
- src/playground/with-layout/datepicker/datepicker-routing.module.ts
- src/playground/with-layout/datepicker/datepicker.module.ts
Closes: #2626 
Add an example to docs how to use `filter` input property.
> docs(datepicker): add filter example

- src/framework/theme/components/cdk/overlay/overlay-trigger.ts
> fix(focus trigger strategy clickout): consider click target

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 7.0.2

- README.md
fix description in README.md file
> chore(readme): remove unnecessary line

- .github/workflows/pr-check.yml
> chore(ci): move tokens to environment variables

- .github/workflows/pr-check.yml
> chore(ci): correct env variables access

- docs/articles/design-system/multiple-runtime-themes.md
Fixes a broken link inside the docs
> docs: fix runtime theme change link

- src/framework/theme/components/tag/tag-list.component.ts
Closes #2925
Handle `FocusMonitor.monitor` first emit on the server platform.
> fix(tag list): prevent initialisation error in Universal

- src/app/app.component.scss
- src/app/app.component.ts
- src/app/layout-direction-toggle/layout-direction-toggle.component.scss
- src/app/layout-theme-toggle/layout-theme-toggle.component.scss
> refactor(playground toolbar): separate tools via divider

- .vscode/settings.json
- angular.json
> chore: add prettier as default formatter for vs code settings

- angular.json
- scripts/docs/config.ts
- scripts/gulp/tasks/config.ts
> fix(7.0.x): change build docs output path

- angular.json
- scripts/docs/config.ts
- scripts/gulp/tasks/config.ts
> fix(8.0.x): change build docs output path

- README.md
- docs/articles/getting-started/what-is-nebular.md
> docs: update browser support

- src/framework/theme/components/cdk/overlay/overlay-trigger.ts
`NbTriggerStrategyBase`'s `isNotOnHostOrContainer`, `isOnHostOrContainer`, `isOnHost`, `isOnContainer` methods now expect `Element` instead of `Event` as the first parameter. Pass `event.target as Element` instead of `event`.
> refactor(overlay trigger): accept Element instead Event

- tools/publish.sh
> chore: correct path for packages to publish

- src/framework/theme/components/context-menu/context-menu.directive.ts
- src/framework/theme/components/layout/layout.component.ts
- src/framework/theme/components/sidebar/sidebar.component.ts
- src/framework/theme/components/tabset/tabset.component.ts
> fix: memory leaks in 7.0.x LTS

- src/framework/theme/components/layout/layout.component.ts
- src/framework/theme/components/tabset/tabset.component.ts
> fix: memory leaks

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 7.0.3

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.ts
- src/framework/theme/package.json
> release: 7.0.4

- src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.spec.ts
- src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.ts
Fix subscription leaks based on number of on stable events
> fix(overlay): take 1 on stable event

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 9.0.2

- src/framework/theme/components/select/select.component.html
Prevent opening select when it was disabled
Closes https://github.com/akveo/nebular/issues/3036
> fix(select): disable opening disabled select after clicking on content

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 9.1.0-rc.2

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 9.1.0-rc.3

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 9.1.0-rc.4

- src/framework/theme/components/select-with-autocomplete/_select-with-autocomplete-filled.scss
- src/framework/theme/components/select-with-autocomplete/_select-with-autocomplete-hero.scss
- src/framework/theme/components/select-with-autocomplete/_select-with-autocomplete-outline.scss
- src/framework/theme/components/select-with-autocomplete/select-with-autocomplete.component.html
- src/framework/theme/components/select-with-autocomplete/select-with-autocomplete.component.ts
select autocomplete width on opening
> fix(select-with-autocomplete): fix select autocomplete width

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 9.1.0-rc.6

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 9.1.0-rc.7

- CHANGELOG.md
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 9.1.0-rc.8

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/components/tabset/tabset.component.ts
- src/framework/theme/package.json
> release: 10.0.0

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 6.2.3

- src/framework/theme/components/autocomplete/autocomplete.directive.ts
> Fix(autocomplete): show options

- angular.json
> fix(docs): remove bootstrap from docs

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/components/tabset/tabset.component.ts
- src/framework/theme/package.json
> release: 11.0.0

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 11.0.1

- tools/gulp/docs/sass-export.ts
> fix(docs): fix docs deployment

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 12.0.0

- packages-smoke/package-lock.json
- packages-smoke/package.json
> chore: update angular/cdk to 17 in package-smoke

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 14.0.1

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/package.json
> release: 14.0.2

- CHANGELOG.md
- docs/versions.json
- package-lock.json
- package.json
- packages-smoke/package-lock.json
- packages-smoke/package.json
- src/framework/auth/package.json
- src/framework/bootstrap/package.json
- src/framework/date-fns/package.json
- src/framework/eva-icons/package.json
- src/framework/firebase-auth/package.json
- src/framework/moment/package.json
- src/framework/security/package.json
- src/framework/theme/components/route-tabset/_route-tabset.component.theme.scss
- src/framework/theme/package.json
- src/framework/theme/styles/core/_mixins.scss
> release: 15.0.0
