akveo/nebular

src/framework/auth/components/auth.component.scss
src/framework/auth/components/auth.component.ts

Currently, if your auth pages get too long, you will start to notice content being cutoff from the page and beyond the scrollbar's range.
This fix removed the justify-content: center and align-items: center from the auth component's SCSS file and adds a margin: auto to the nb-card-body so that it can remain centered. This fix is coming after hours of researching ending up here:
[https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container](https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container)

Fixed scrollbar cutoff issue with auth

---

.travis.yml
karma.conf.js
scripts/ci/browserstack/config.js
scripts/ci/browserstack/start-tunnel.sh

…ag, so that menu height calculation works properly

fix(tavis): fix karma config for browserstack

---

e2e/menu.e2e-spec.ts
src/framework/theme/components/sidebar/sidebar.component.ts

fix(sidebar): only expand sidebar when item has children elements

---

docs/articles/auth-ui.md
src/app/app.module.ts
src/framework/auth/auth.options.ts
src/framework/auth/components/auth-block/auth-block.component.scss
src/framework/auth/components/login/login.component.ts
src/framework/auth/components/register/register.component.ts

Links are placed at the bottom of login and register pages, accepts `link`, `url`, `title` and `icon` class.
Closes: #171

feat(auth): ability to configure social link

---

docs/output.json
src/app/user-test/user-test.component.ts
src/framework/theme/components/user/_user.component.theme.scss
src/framework/theme/components/user/user.component.html
src/framework/theme/components/user/user.component.scss
src/framework/theme/components/user/user.component.ts
src/framework/theme/styles/themes/_cosmic.scss
src/framework/theme/styles/themes/_default.scss

Remove user component context menu. User context menu example will be created in the ngx-admin with popover component.

refactor(theme): remove user context menu

---

docs/output.json
src/framework/theme/components/context-menu/context-menu.component.ts
src/framework/theme/components/context-menu/context-menu.directive.ts

Add capability pass NbMenu tag through NbContextMenu

refactor(context-menu): add tag which will be passed to the inner NbMenu

---

src/framework/auth/services/interceptors/jwt-interceptor.ts

Solves an issue where the header is set in the interceptor even if we don't have any token.
Solves issue #293

Set Authorization header only if the token is valid

---

e2e/menu.e2e-spec.ts
src/app/menu-test/menu-test.component.ts
src/framework/theme/components/menu/menu-item.component.html
src/framework/theme/components/menu/menu.component.ts
src/framework/theme/components/menu/menu.service.ts

feat(menu): add support for query parameters (#283)

---

e2e/menu.e2e-spec.ts
src/app/menu-test/menu-test.component.ts
src/framework/theme/components/menu/menu-item.component.html
src/framework/theme/components/menu/menu.component.ts

fix(menu): avoid DOM elements creation for hidden menu items (fix#270)

---

e2e/menu.e2e-spec.ts
src/app/app.routes.ts
src/app/menu-test/menu-test.component.ts
src/framework/theme/components/menu/menu.component.ts
src/framework/theme/components/menu/menu.service.ts
src/framework/theme/components/menu/menu.spec.ts
src/framework/theme/components/menu/url-matching-helpers.ts

Apply defaults for menu items
+ fix logic for inference of selected items from URL for fragment and queryParams cases
+ e2e tests for fragment and queryParams in menu

feat(menu): apply default values for menuItems

---

src/framework/theme/components/menu/menu.component.ts

To animate menu expanding we need to know height of all expoanded children.
Since children cann't be accessed before AfterViewInit hook, we have to calc
and set 'maxHeight' there, but it causing ExpressionChangedAfterItHasBeenCheckedError
error. Since 'maxHeight' can't be calculated earlier, we have to trigger change detection
again. This is a common workaround for this error.
Fix #263

fix(menu): trigger change detection after setting max-height

---

docs/app/app.component.ts
docs/app/docs/page/page.component.ts
docs/app/docs/utils/analytics.service.ts
docs/app/homepage/homepage.component.ts
src/framework/theme/components/layout/layout.component.ts
src/framework/theme/components/menu/menu.component.ts
src/framework/theme/components/popover/helpers/adjustment.helper.ts
src/framework/theme/components/popover/helpers/adjustment.spec.ts
src/framework/theme/components/popover/helpers/positioning.helper.ts
src/framework/theme/components/popover/helpers/positioning.spec.ts
src/framework/theme/components/popover/helpers/trigger.helper.ts
src/framework/theme/services/spinner.service.ts
src/framework/theme/theme.module.ts
src/framework/theme/theme.options.ts

fix: provide browser globals with injection tokens

---

docs/articles/auth-install.md
docs/articles/auth-intro.md
docs/articles/auth-strategy.md
docs/articles/auth-token.md
docs/articles/auth-ui.md
docs/articles/index.md
docs/structure.ts
src/app/app.module.ts
src/framework/auth/auth.module.ts
src/framework/auth/auth.options.ts
src/framework/auth/components/login/login.component.ts
src/framework/auth/components/logout/logout.component.ts
src/framework/auth/components/register/register.component.ts
src/framework/auth/components/request-password/request-password.component.ts
src/framework/auth/components/reset-password/reset-password.component.ts
src/framework/auth/providers/index.ts
src/framework/auth/services/auth.service.ts
src/framework/auth/services/auth.spec.ts
src/framework/auth/strategies/auth-strategy.ts
src/framework/auth/strategies/default/default-strategy-options.ts
src/framework/auth/strategies/default/default-strategy.spec.ts
src/framework/auth/strategies/default/default-strategy.ts
src/framework/auth/strategies/dummy/dummy-strategy-options.ts
src/framework/auth/strategies/dummy/dummy-strategy.ts
src/framework/auth/strategies/index.ts

- term auth `provider` renamed to `strategy` to eliminate intersection with Angular providers
- `NbDummyAuthProvider` renamed to `NbDummyAuthStrategy`
- `NbEmailPassAuthProvider` renamed to `NbDefaultAuthStrategy`
- `NbAbstractAuthProvider` renamed to `NbAuthStrategy`
- `NbAuthModule.forRoot({ forms.login.provider })` changed to `NbAuthModule.forRoot({ forms.login.strategy })`
```
`NbAuthModule.forRoot({
forms: {
login: {
strategy: 'email', // provider -> strategy
},
},
})`
```

refactor(auth): rename auth provider to strategy

---

docs/articles/auth-install.md
docs/articles/auth-strategy.md
docs/articles/auth-token.md
docs/articles/auth-ui.md
src/app/app.module.ts
src/framework/auth/auth.module.ts
src/framework/auth/auth.options.ts
src/framework/auth/services/auth.service.ts
src/framework/auth/services/auth.spec.ts
src/framework/auth/strategies/auth-strategy-options.ts
src/framework/auth/strategies/auth-strategy.ts
src/framework/auth/strategies/dummy/dummy-strategy-options.ts
src/framework/auth/strategies/dummy/dummy-strategy.ts
src/framework/auth/strategies/index.ts
src/framework/auth/strategies/password/password-strategy-options.ts
src/framework/auth/strategies/password/password-strategy.ts

Refactor strategies object to an array and pass strategy options through `setup` method.
Strategy name moved inside of options object.
Auth module options' `strategies` list changed from a key=>value object to an array.
So now instead of
```
...
strategies: {
email: {
service: NbEmailPassAuthProvider,
config: { ... }
}
}
```
we do this:
```
strategies: [
NbPasswordAuthStrategy.setup({ name: 'email', ... }),
]
```
This way we can type-check the configuration object for each strategy specified.

refactor(auth): pass strategies through special `setup` method

---

src/backend/app.js
src/framework/auth/providers/abstract-auth.provider.ts
src/framework/auth/providers/dummy-auth.provider.ts
src/framework/auth/providers/email-pass-auth.options.ts
src/framework/auth/providers/email-pass-auth.provider.ts
src/framework/auth/providers/email-pass-auth.spec.ts
src/framework/auth/services/auth.service.ts
src/framework/auth/services/auth.spec.ts

Added a way to refresh tokens inside the AuthService. This is not yet hooked anywhere, but it could be hooked inside an interceptor, as I've seen mentionned in #260. Typically, I think the refresh token would be stored in a HttpOnly cookie. This also addresses #362.
```
this.authService.refreshToken('email').subscribe((result: NbAuthResult) => {
//Do something
});
```
I have also fixed #389, which involved changing `private getProvider` to `protected getProvider`.
Please let me know if I need to change anything!

feat(auth): add support for refresh tokens

---

e2e/context-menu.e2e-spec.ts
src/app/context-menu-test/context-menu-test.component.ts
src/framework/auth/UPGRADE.md
src/framework/theme/components/context-menu/context-menu.directive.ts

fix(context-menu): hide on menu item click

---

docs/articles/rtl.md

fix(docs): add missing operator

---

src/framework/theme/styles/global/bootstrap/_default-buttons.scss
src/framework/theme/styles/themes/_cosmic.scss
src/framework/theme/styles/themes/_default.scss

Fix color for focused outline buttons, add new variable btn-outline-focus-fg

fix(theme): add new variable for focused outline buttons

---

docs/articles/security-multiple-roles.md
src/framework/security/services/access-checker.service.ts
src/framework/security/services/access-checker.spec.ts
src/framework/security/services/role.provider.ts

feat(security): add ability to assign multiple roles to a user

---

src/framework/theme/components/checkbox/checkbox.component.ts
src/framework/theme/components/checkbox/checkbox.spec.ts

When using nb-checkbox with reactive forms, disabling the form control does not disable the underlying input. Implementing the `setDisabledState` method fixes this issue. See #296 for the initial report.

fix(checkbox): fix disable state with reactive forms

---

src/framework/theme/package.json
src/framework/theme/styles/global/_normalize.scss

- remove normalize as Nebular theme dependency
- copy normalize into Nebular theme styles

refactor(theme): remove normalize as dep and just copy it

---

src/playground/dialog/dialog-showcase.component.ts
src/playground/dialog/dialog-template.component.ts
src/playground/toastr/toastr-positions.component.ts
src/playground/toastr/toastr-showcase.component.ts

fix(playground): use nebular buttons in examples

---

src/framework/theme/components/checkbox/checkbox.component.ts
src/framework/theme/components/datepicker/datepicker.component.ts
src/framework/theme/components/datepicker/datepicker.directive.ts
src/framework/theme/components/radio/radio-group.component.ts
src/framework/theme/components/radio/radio.component.ts
src/framework/theme/components/radio/radio.spec.ts
src/framework/theme/components/select/select.component.html
src/framework/theme/components/select/select.component.ts

Fix `ControlValueAccessor` implementation in nebular form controls.
Closes #367.

fix(form controls): mark as touched

---

src/framework/theme/components/toastr/toastr-container.component.ts

Angular animations have a bug. All properties have to be expanded to work properly in firefox and edge. So, I've just expanded the margin.
Closes #865

fix(toastr): animations in firefox and edge

---

src/framework/theme/components/select/select.component.html

fix(select): add type button, stop forms submitting

---

src/framework/theme/components/cdk/overlay/overlay-trigger.spec.ts
src/framework/theme/components/cdk/overlay/overlay-trigger.ts

Add filter to `NbHoverTrigger.show$` to stop firing show events if container already exists.
Closes #900

fix(overlay): hover trigger stop fire show if container already exists

---

src/framework/theme/components/popover/popover.directive.ts

fix(popover): Null check the ref before disposing

---

package-lock.json
package.json
scripts/gulp/tasks/bundle/rollup-config.ts
src/framework/theme/components/cdk/overlay/mapping.ts
src/framework/theme/components/cdk/overlay/overlay-container.ts
src/framework/theme/components/dialog/dialog.service.spec.ts
src/framework/theme/components/popover/popover.component.ts
src/framework/theme/components/popover/popover.spec.ts
src/framework/theme/package.json

fix(popover): fix template context not being passed, update cdk to 7.2.1

---

src/framework/theme/components/layout/layout.component.ts

fix(layout): typo in basic usage example

---

docs/articles/auth-custom-ui.md

The library's url of `login.component.html` is wrong. Idk the reason why the url point to a 404 page in github. And I compareed the right url and wrong url. The difference of them is letter 'v'.

fix the library's url of `login.component.html`

---

src/framework/theme/components/toastr/toastr.service.spec.ts
src/framework/theme/components/toastr/toastr.service.ts

fix(toastr): recreate container when it's not attached to dom

---

docs/structure.ts
src/app/playground-components.ts
src/framework/theme/components/tree-grid/data-source/tree-grid-data-source.ts
src/framework/theme/components/tree-grid/data-source/tree-grid-data.service.ts
src/framework/theme/components/tree-grid/data-source/tree-grid-filter.service.ts
src/framework/theme/components/tree-grid/data-source/tree-grid.model.ts
src/framework/theme/components/tree-grid/data-source/tree-grid.service.ts
src/framework/theme/components/tree-grid/tree-grid-cell.component.ts
src/framework/theme/components/tree-grid/tree-grid.component.spec.ts
src/framework/theme/components/tree-grid/tree-grid.component.ts
src/playground/with-layout/tree-grid/tree-grid-basic.component.ts
src/playground/with-layout/tree-grid/tree-grid-custom-icons.component.ts
src/playground/with-layout/tree-grid/tree-grid-custom-node-structure.component.ts
src/playground/with-layout/tree-grid/tree-grid-disable-click-toggle.component.ts
src/playground/with-layout/tree-grid/tree-grid-filterable.component.ts
src/playground/with-layout/tree-grid/tree-grid-responsive.component.ts
src/playground/with-layout/tree-grid/tree-grid-routing.module.ts
src/playground/with-layout/tree-grid/tree-grid-showcase.component.ts
src/playground/with-layout/tree-grid/tree-grid-sortable.component.ts
src/playground/with-layout/tree-grid/tree-grid.module.ts

Custom getters for node properties

refactor(tree-grid): allow specify getters for node properties

---

src/framework/date-fns/services/date-fns-date.service.spec.ts
src/framework/date-fns/services/date-fns-date.service.ts
src/framework/moment/services/moment-date.service.spec.ts
src/framework/moment/services/moment-date.service.ts
src/framework/theme/components/datepicker/datepicker-adapter.spec.ts
src/framework/theme/components/datepicker/datepicker-adapter.ts

fix(date service): prevent format calls if date isn't passed

---

src/framework/theme/components/calendar-kit/components/calendar-month-picker/calendar-month-picker.component.ts
src/framework/theme/components/calendar-kit/components/calendar-year-picker/calendar-year-picker.component.ts
src/framework/theme/components/calendar-kit/components/index.ts
src/framework/theme/components/calendar/base-calendar.component.ts
src/framework/theme/components/datepicker/datepicker.component.ts
src/framework/theme/components/datepicker/datepicker.spec.ts

Fixes #1081 (not initial issue but [comment](https://github.com/akveo/nebular/issues/1081#issuecomment-472041814))

fix(datepicker):  start from date typed in input

---

src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay-handler.spec.ts
src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay-handler.ts
src/framework/theme/components/cdk/overlay/overlay-trigger.spec.ts
src/framework/theme/components/cdk/overlay/overlay-trigger.ts
src/framework/theme/components/datepicker/datepicker.component.ts
src/framework/theme/components/select/select.component.ts

Closes #1289, #1292, #1290, #1292, #1273
Rewrite overlay triggers to close them manually calling **destroy()** method.

refactor(cdk): destroy overlay triggers manually

---

src/framework/theme/components/select/select.component.ts
src/framework/theme/components/select/select.spec.ts

Fixes case when component was destroyed before calling init hook.

fix(select): prevent dispose call on uninitialized properties

---

src/framework/theme/components/select/option.component.ts
src/framework/theme/components/select/select.component.ts
src/framework/theme/components/select/select.spec.ts

Previously NbOptionComponent 'selectionChange' where emitted only when
option clicked, ignoring cases where select/deselect methods were called
from NbSelectComponent.
Also deprecates NbSelectComponent 'selectionChange' property.
We already has 'selectedChange' for this. Also 'selectionChange' name is
a bit confusing since it emits only when option clicked.

fix(option): emit selection change when selection is changed

---

src/framework/theme/components/calendar-kit/components/calendar-month-picker/calendar-month-picker.component.spec.ts
src/framework/theme/components/calendar-kit/components/calendar-month-picker/calendar-month-picker.component.ts

 fix(month picker): prevent duplicates

---

src/framework/theme/components/select/select.spec.ts

There is two task pending. One from button setTimeout and another from
spinner service.
There is two task pending. One from button setTimeout and another from
spinner service (I have no idea why spinner micro task showed up. It's code here since 2017).

test(select): flush pending microtasks from other components

---

src/framework/theme/components/cdk/overlay/overlay-container.spec.ts
src/framework/theme/components/cdk/overlay/overlay-container.ts
src/framework/theme/components/popover/popover.component.ts
src/framework/theme/components/window/window.component.ts

fix(overlay): set context on component portals before first cd run

---

src/framework/theme/components/select/select.component.ts
src/framework/theme/components/select/select.spec.ts

Reset emitted null as a select value for multiple select which caused `Can't assign a single value if select is marked as multiple` error when trying to set `null` value back (two-way data binding).

fix(select): emit array when resetting multiple select

---

src/framework/theme/components/tabset/tabset.component.spec.ts
src/framework/theme/components/tabset/tabset.component.ts

fix(tabset): prevent select call if no active tab found

---

angular.json

Set `rebaseRootRelativeCssUrls` to enable legacy behavior when css absolute urls prefixed with base url. We need this until we have `/nebular/next` docs.
Prefixing removed in angular-cli#13684

fix(docs): prefix root css urls with base path

---

docs/articles/migration/350-400.md

fix(docs): update changed component theme vars link

---

src/framework/theme/components/select/_select.component.theme.scss

Fixes transparent gap between options on iOS when zoomed in

fix(select): transparent gap between options

---

CHANGELOG.md
docs/articles/migration/350-400.md
src/framework/theme/components/icon/icon.component.ts

* Wrong import statement of NbEvaIconsModule (`form` ➡️ `from`)

fix(docs): wrong NbEvaIconsModule import

---

src/framework/theme/components/toastr/_toast.component.theme.scss

The icon is not shrunk when title or message is too big

fix(toastr): icon size shrink

---

src/framework/theme/components/select/select.component.ts
src/framework/theme/components/select/select.spec.ts

Fixes case when `nb-select` itself has padding leading to overlay being disconnected from a button or having width more than a button.

fix(select): make options list same width as button

---

src/framework/theme/components/alert/alert.component.ts

Import `NbButtonModule` to your feature module.
NbAlertModule must be imported not NbButtonModule

docs(alert): specify a correct module to import

---

src/framework/theme/components/select/_select-outline.scss
src/framework/theme/styles/themes/_corporate.scss
src/framework/theme/styles/themes/_mapping.scss

Fixes select in corporate theme. Now both select and options list has same border.
Also removes `select-options-list-border-color` since it always overwritten by `select-<appearance>-options-list-border-color`.
And `select-outline-<status>-adjacent-border-color`, `select-outline-<status>-adjacent-border-style`, `select-outline-<status>-adjacent-border-width` theme variables were unused. I added appropriate styles for this properties.

fix(select): add theme property for open select border

---

src/framework/theme/components/stepper/stepper.component.ts

fix(stepper): add missing stepper provider

---

package.json

No need to run `docs:prepare` before `docs:build` as it's first command
of `docs:build`.

chore(ci): remove unnecessary command

---

src/framework/theme/components/layout/_layout.component.theme.scss

Fixes gaps between `nb-layout-header` and inner `nav` in cases when
`nav` width is smaller than `nb-layout-header` width.

fix(layout): set header background color on host element

---

src/app/playground-components.ts
src/framework/theme/components/card/card.component.ts
src/framework/theme/styles/themes/_mapping.scss
src/playground/with-layout/card/card-routing.module.ts
src/playground/with-layout/card/card-sizes-combinations.component.html
src/playground/with-layout/card/card-sizes-combinations.component.scss
src/playground/with-layout/card/card-sizes-combinations.component.ts
src/playground/with-layout/card/card.module.ts

tiny + tiny = medium
tiny + small = large
tiny + medium = giant

fix(card): make two smaller cards same height as one large

---

src/framework/theme/styles/global/typography/_typography.scss

This allows overriding elements text color who has it set since
selectors have the same weight but text color classes defined later.

fix(typography): declare text color classes at the bottom

---

src/framework/theme/components/select/select.component.html
src/framework/theme/components/select/select.spec.ts

fix(select): prevent opening of disabled select when clicking on toggle

---

src/framework/theme/components/cdk/adapter/adapter.module.ts
src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.spec.ts
src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.ts

fix(dynamic overlay): recreate overlay when overlay container change

---

src/framework/theme/components/actions/actions.component.ts
src/framework/theme/components/icon/icon.component.ts
src/framework/theme/components/icon/icon.spec.ts
src/framework/theme/components/menu/menu-item.component.html
src/framework/theme/components/menu/menu.service.ts
src/framework/theme/components/route-tabset/route-tabset.component.ts
src/framework/theme/components/tabset/tabset.component.ts
src/framework/theme/components/toastr/toast.component.html
src/framework/theme/components/toastr/toast.component.ts
src/framework/theme/components/toastr/toastr-config.ts
src/framework/theme/components/tooltip/tooltip.component.ts
src/framework/theme/components/tooltip/tooltip.directive.ts
src/playground/with-layout/action/action-showcase.component.html
src/playground/with-layout/action/action-showcase.component.ts
src/playground/with-layout/menu/menu-showcase.component.ts
src/playground/with-layout/tabset/tabset-icon.component.html
src/playground/with-layout/tabset/tabset-icon.component.ts
src/playground/with-layout/toastr/toastr-icon.component.ts
src/playground/with-layout/tooltip/tooltip-with-icon.component.html

feat: accept icon config in components which use nb-icon

---

src/framework/theme/schematics/ng-add/index.ts
src/framework/theme/schematics/util/package.ts

Using `angular/core` package version for `schematics/angular` it will sometimes raise "No matching version found" error because they are in sync only with the major versions. The `schematics` scoped packages are under the Angular CLI repo and they will be released together. By using the CLI version when add the `schematics/angular` package to the devDependencies we will, hopefully, be sure that the version exists and is published to npm.
Closes #1864

fix(schematics): use cli version for schematics/angular package

---

docs/articles/auth/backend-api.md
docs/structure.ts

docs(auth): add backend api endpoints

---

src/framework/theme/components/calendar-kit/components/calendar-day-picker/calendar-day-picker.component.scss
src/framework/theme/components/calendar-kit/components/calendar-day-picker/calendar-day-picker.component.ts
src/framework/theme/components/calendar-kit/components/calendar-week-number/nb-calendar-week-number.component.ts

 fix(calendar): use last defined week day to determine week number

---

src/framework/theme/components/context-menu/context-menu.directive.ts

The documentation of this component at https://akveo.github.io/nebular/docs/components/context-menu/overview#nbcontextmenudirective is broken becasue an extra asterisk in the code.
Fix broken documentation at https://akveo.github.io/nebular/docs/components/context-menu/overview#nbcontextmenudirective

docs(context menu): remove extra character breaking overview text

---

docs/app/@theme/services/structure.service.ts

If in `structure.ts` we have repeating sources, overview block of component page will produce repeating titles. To avoid this behaviour mark and skip already checked components (sources).

docs: skip repeating sources to avoid extra title producing

---

src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay-handler.spec.ts
src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay-handler.ts
src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.spec.ts
src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.ts
src/framework/theme/components/popover/popover.directive.ts
src/framework/theme/components/popover/popover.spec.ts
src/framework/theme/components/tooltip/tooltip.directive.ts
src/framework/theme/components/tooltip/tooltip.spec.ts

Adds `nbPopoverShowStateChange` output to the popover directive.
Also adds ability to use popover as a template variable:
```
<button nbPopover="..." #popover="nbPopover">...</button>
Is shown: {{ popover.isShown }}
```
Private popover directive properties changed to protected to simplify extension.
Add input for popover css class.
All above applies to tooltip as well.

feat(popover, tooltip): add shown state api

---

src/framework/theme/components/datepicker/datepicker.component.ts
src/framework/theme/components/datepicker/datepicker.spec.ts

Prevents the `DatePickerComponent` from crashing if it is destroyed shortly after its creation. View this issue for a more detailed description: https://github.com/akveo/nebular/issues/2007.
This error occurs without the null check:

fix(datepicker): check trigger strategy is defined before destroying

---

src/framework/theme/components/datepicker/datepicker.directive.ts
src/framework/theme/components/radio/radio-group.component.ts

We need to call touched callback on each blur event to run control update and validation as Angular Forms Api relies on it when configured to update on `blur`.

fix(datepicker, radio): always call touched callback

---

src/framework/theme/components/cdk/overlay/overlay-position.spec.ts
src/framework/theme/components/cdk/overlay/overlay-position.ts
src/framework/theme/components/tooltip/tooltip.component.scss
src/playground/with-layout/tooltip/tooltip-placements.component.html

Also fixes positions order for components with preferred physical position (left and right).

fix(tooltip): add angular positions classes

---

src/framework/theme/components/icon/icon.component.ts
src/framework/theme/components/icon/icon.spec.ts

Fix icon inner html NULL in MS Edge (https://github.com/akveo/nebular/issues/1962)

fix(icon): fix NULL content render in MS Edge

---

src/framework/auth/components/login/login.component.html
src/framework/auth/components/register/register.component.html
src/framework/auth/components/request-password/request-password.component.html
src/framework/auth/components/reset-password/reset-password.component.html

On Auth components with https://github.com/akveo/nebular/pull/2047/files# changes:
Warning message is triggered when nbInput component with status input attribute is an empty string.
On login component there is an occurrence with this issue. Replace empty string with `basic` value on status attribute.

 fix(auth): use basic status instead deprecated empty string

---

src/framework/theme/components/cdk/adapter/adapter.module.ts

To be able explicitly specify Nebular class as injection token.

fix: provide Nebular scroll services adapters

---

src/framework/theme/components/route-tabset/route-tabset.component.scss

Moves `@include nb-ltr` and `@include nb-rtl` under `host` selector as required by mixin.
Also removes default `ul` padding.
And `:host.full-width` rewritten to correct form `:host(.full-width)`.

fix(route tabset): tab icon margin

---

src/framework/theme/components/button/_button.component.theme.scss
src/framework/theme/components/button/button.component.scss

Disables text decoration on button links. Setting `text-decoration` under `:host` selector isn't enough after #2169 as it adds `.nb-theme-<theme-name> a` selector which has more weight. Setting `text-decoration` in theme file fixes the problem.

fix(button link): remove text decoration

---

docs/articles/getting-started/what-is-nebular.md

Fixes trivial typo in `what-is-nebular.md`: librariws -> libraries
Resolves #2164

chore(docs): fix typo in getting started

---

src/framework/theme/components/menu/menu.component.scss

:host color style overrides color set in theme file.

fix(menu): prevent color override in css vars mode

---

src/framework/auth/strategies/oauth2/oauth2-strategy.options.ts
src/framework/auth/strategies/oauth2/oauth2-strategy.ts
src/framework/auth/strategies/password/password-strategy-options.ts
src/framework/auth/strategies/password/password-strategy.ts
src/playground/without-layout/auth/auth.module.ts

Closes #1246.
`requireValidToken` set to true by default.
Now if response contains invalid token `NbAuthIllegalTokenError` is thrown.
To enable old behavior, set `requireValidToken: false` in the auth strategy method config, e.g.:
```
NbPasswordAuthStrategy.setup({
// ...
login: {
// ...
requireValidToken: false,
},
});
```
or
```
NbOAuth2AuthStrategy.setup({
// ...
authorize: {
// ...
requireValidToken: false,
},
});
```

refactor(auth): require valid token by default

---

src/framework/theme/components/autocomplete/autocomplete.directive.ts

An input to control the focus behaviour when the control value changes
Ref #2355 
Introduces an Input to NbAutocompleteDirective to control the focus behaviour when the control value is set (-> writeValue).

feat(autocomplete): input for focus on value change

---

src/framework/theme/components/button/button.component.ts

fix(nbButton): allow specifying custom tabindex

---

src/framework/theme/components/form-field/_form-field.component.theme.scss
src/framework/theme/components/form-field/form-field-control.ts
src/framework/theme/components/form-field/form-field.component.ts
src/framework/theme/components/input/input.directive.ts
src/framework/theme/components/select/select.component.ts
src/framework/theme/styles/themes/_mapping.scss

fix(form field): addon alignment

---

CHANGELOG.md
docs/versions.json
package-lock.json
package.json
packages-smoke/package-lock.json
packages-smoke/package.json
src/framework/auth/package.json
src/framework/bootstrap/package.json
src/framework/date-fns/package.json
src/framework/eva-icons/package.json
src/framework/firebase-auth/package.json
src/framework/moment/package.json
src/framework/security/package.json
src/framework/theme/package.json

release: 6.0.0

---

src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.spec.ts
src/framework/theme/components/cdk/overlay/dynamic/dynamic-overlay.ts
src/framework/theme/components/context-menu/context-menu.directive.ts
src/framework/theme/components/popover/popover.directive.ts
src/framework/theme/components/tooltip/tooltip.directive.ts

The main fix is 419ca7c. After the change, dynamic overlay unsubscribes from `zone.onStable` once overlay got destroyed. Before, every time the `show` method was called, we were creating an additional subscription, which leads to multiple `updatePosition` calls.
Changes from 3379373 is an additional fix, which ensures dynamic overlay context and config properties updating only once some property actually changed. Before, because of we were passing a new object to `overlayConfig` and `context` methods overlay was recreated on every `ngOnChanges` run. See commit description for details. UPD: 1763905 is a refactor of the way overlay config objects updated. First I decided to use change object from `OnChanges` hook, but we have tests which check if direct manipulation of component instance …

fix(dynamic overlay): prevent multiple onStable subscriptions

---

src/framework/theme/components/toastr/toast.component.ts

please correct the typo in the documentation related to border and background color when toast hovered

chore(docs): correct toastr theme variable names

---

src/framework/theme/components/accordion/_accordion.component.theme.scss

This way `nb-accordion` inner items (like `nb-accordion-item-header`, `nb-accordion-item`, `nb-accordion-item-body`) keep their styles when are placed outside `nb-accordion` element (for example, when used as `cdkDrag` as when element dragged it placed in the body).

fix(accordion): extract inner elements styles outside accordion

---

src/framework/theme/components/calendar-kit/components/calendar-day-picker/calendar-day-picker.component.ts
src/framework/theme/components/calendar/calendar-range-day-cell.component.ts
src/framework/theme/components/calendar/calendar-range-month-cell.component.ts
src/framework/theme/components/calendar/calendar-range-year-cell.component.ts
src/framework/theme/components/datepicker/datepicker.component.ts

d0850d4 is the main fix to handle `null`s in `date` and `selecteValue` properties. `date` could be null because of `[boundingMonth]="false"`, see commit description for details.
f5e2a82 and ad6442f are companion fixes for the issues I noticed when I was fixing the main issue.
f5e2a82 - input changes won't be picked up when the picker opens. See the commit description for details.
ad6442f - because `boundingMonth` property value affects bounding month `date` property, day picker should regenerate `weeks` when property change. See the commit description for details.

fix(calendar range cells): handle unset date or selectedValue

---

src/framework/theme/components/toggle/_toggle.component.theme.scss

Use SASS interpolation to compile value properly within CSS `calc` function
Closes https://github.com/akveo/nebular/issues/2293

fix(toggle): alignment of toggle switches

---

src/framework/theme/components/checkbox/checkbox.component.ts
src/framework/theme/components/checkbox/checkbox.spec.ts

`NbCheckboxComponent.value` and `NbCheckboxComponent.valueChange` properties removed. Use `checked` and `checkedChange` accordingly.

feat(checkbox): remove deprecated value input

---

src/framework/theme/components/popover/popover.directive.ts
src/framework/theme/components/tooltip/tooltip.directive.ts

Falsy adjustment values no longer become converted to `NbAdjustment.NOOP`,
pass `NbAdjustment.NOOP` instead.

feat(tooltip, popover): remove ability to use falsy adjustment

---

src/framework/theme/components/toastr/toast.component.html
src/framework/theme/components/toastr/toast.component.ts
src/framework/theme/components/toastr/toastr-config.ts

`NbToastrConfig.iconPack` property remove. You can set icon pack via `icon` property:
```
const toastrConfig = {
// ...
icon: { icon: 'star', pack: 'eva' },
}
```
`NbToastComponent.iconPack` and `NbToastComponent.iconConfig` properties removed.
Use `icon` property instead.

feat(toastr): remove deprecated iconPack property

---

src/framework/theme/components/autocomplete/autocomplete.directive.ts

`renderer` constructor parameter is now required.

feat(autocomplete): make renderer constructor parameter required

---

src/framework/theme/components/sidebar/sidebar.component.ts
src/framework/theme/components/sidebar/sidebar.spec.ts

568497b is the fix. The sidebar will expand when `responsive` is set to `false`. When `responsive` is set to `true` sidebar will check the current breakpoint to determine the state.
a92bc99 - additional fix to unsubscribe from observables on component destroy.
5608742, 477110e - small fix/refactoring to prevent `stateChange` emission when value didn't change.

fix(sidebar): update state when responsive setting change

---

src/framework/theme/components/timepicker/timepicker.directive.ts

fix(timepicker): save lastInputValue when changed via form api

---

src/framework/theme/components/cdk/overlay/overlay-trigger.ts

Click event is fired after focus in/out, so check of event target could be not `document.activeElement`

fix(focus trigger strategy): detect click out via activeElement

---

src/framework/theme/components/cdk/overlay/overlay-container.ts
src/framework/theme/components/window/window-ref.ts
src/framework/theme/components/window/window.component.ts

Closes #2367 
Added `componentInstance` property to `NbWindowRef` contains the instance of the component opened into he window.
How to use: 
```
// window component
...
onAdd = new EventEmitter();
onButtonClick() {
this.onAdd.emit();
}
...
```
```
// parent component
...
constructor(private windowService: NbWindowService) {}
openWindow() {
let windowRef<Component> = this.windowService.open(Component);
const sub = windowRef.componentInstance.onAdd.subscribe(() => {
// do something
});
windowRef.onClose().subscribe(() => {
// unsubscribe onAdd
});
}
...
```

feat(window): add component instance property to window ref

---

src/framework/moment/services/moment-date.service.ts

When manually typing the date into the input field, the DatePicker uses the provided DateFormat.
How to use:
```
@NgModule({
imports: [
NbDatepickerModule.forRoot(),
NbMomentDateModule,
...
],
providers: [{provide: LOCALE_ID, useValue: 'ru-RU'}],
})
```
Closes #2080

fix(moment date service): use locale format by default

---

src/framework/theme/components/button-group/button-group.component.ts
src/framework/theme/components/button-group/button-toggle.directive.ts

Closes #2773 
In `<nb-button-group>` clicking 2 times on the same button don't remove the pressed state (similar to the radio group).

fix(button group): prevent unpress in single mode button group

---

packages-smoke/e2e/.eslintrc.json
packages-smoke/e2e/protractor.conf.js

Fixes case when downloaded chrome driver version doesn't match installed Chrome version.
Also, adds missing ESLint config file for `packages-smoke/e2e` project to specify `protractor.config.js` environment and pass pre-commit linting.

chore(ci e2e): use preinstalled Chrome driver

---

.github/workflows/pr-check.yml

For PRs from repo branches
Narrow push trigger to the master branch. Otherwise PRs from branches in the `akveo/nebular` repository trigger pr-check workflow twice.

chore(ci): prevent duplicate workflow run

---

src/framework/theme/components/sidebar/sidebar.component.ts

`NbSidebarComponent.toggleResponsive` method removed. Toggle `responsive` property.
`NbSidebarComponent`'s `STATE_EXPANDED`, `STATE_COLLAPSED`, `STATE_COMPACTED` static properties removed. Use `NbSidebarState` type values (`'expanded'`, `'collapsed'`, `'compacted'`).
`NbSidebarComponent`'s `RESPONSIVE_STATE_MOBILE`, `RESPONSIVE_STATE_TABLET`, `RESPONSIVE_STATE_PC`  static properties removed. Use `NbSidebarResponsiveState` type values (`'mobile'`, `'tablet'`, `'pc'`).

refactor(sidebar): remove deprecated properties

---

src/framework/auth/styles/prebuilt/components-custom-properties.scss
src/framework/auth/styles/prebuilt/corporate-custom-properties.scss
src/framework/auth/styles/prebuilt/cosmic-custom-properties.scss
src/framework/auth/styles/prebuilt/dark-custom-properties.scss
src/framework/auth/styles/prebuilt/default-custom-properties.scss
src/framework/bootstrap/styles/prebuilt/components-custom-properties.scss
src/framework/bootstrap/styles/prebuilt/corporate-custom-properties.scss
src/framework/bootstrap/styles/prebuilt/cosmic-custom-properties.scss
src/framework/bootstrap/styles/prebuilt/dark-custom-properties.scss
src/framework/bootstrap/styles/prebuilt/default-custom-properties.scss
src/framework/theme/styles/_theming-variables.scss
src/framework/theme/styles/core/theming/_install.scss
src/framework/theme/styles/prebuilt/components-custom-properties.scss
src/framework/theme/styles/prebuilt/corporate-custom-properties.scss
src/framework/theme/styles/prebuilt/cosmic-custom-properties.scss
src/framework/theme/styles/prebuilt/dark-custom-properties.scss
src/framework/theme/styles/prebuilt/default-custom-properties.scss

Adds `{auth,bootstrap,theme}/styles/prebuilt/components-custom-properties.scss` to separate theme files from components styles. This way user could include component styles once, and then add one or more theme files that only contain theming properties settings.

feat: add prebuilt themes with custom properties

---

src/framework/theme/components/layout/layout.component.ts

NbLayoutScrollService.scrollPositionReq$ may be emited before view init
Update layout scroll logic update identically to 9.0.0

fix(layout): move scroll position update in constructor

---

src/framework/theme/components/timepicker/timepicker.directive.ts

"Counterclockwise" position adjustment prevents timepicker from going outside the window horizontally
Before
After

fix(timepicker): change position adjustment to "counterclockwise"

---

src/app/playground-components.ts
src/framework/theme/components/form-field/form-field.component.scss
src/framework/theme/components/option/option.component.scss
src/framework/theme/components/select/select.component.html
src/framework/theme/components/select/select.component.scss
src/framework/theme/components/select/select.component.ts
src/framework/theme/components/select/select.module.ts
src/framework/theme/components/select/select.spec.ts
src/playground/with-layout/select/select-routing.module.ts
src/playground/with-layout/select/select-search-showcase.component.html
src/playground/with-layout/select/select-search-showcase.component.ts
src/playground/with-layout/select/select.module.ts

feat(select): options search

---

src/framework/theme/components/select-with-autocomplete/select-with-autocomplete.component.html
src/framework/theme/components/select-with-autocomplete/select-with-autocomplete.component.ts
src/playground/with-layout/select/select-autocomplete-showcase.component.html
src/playground/with-layout/select/select-autocomplete-showcase.component.ts

- fix opening options after `multiple` changed
- fix setting autocomplete value with spaces at start and end
- fix double-click closing

fix(select-with-autocomplete): improve select open after input changed

---

src/framework/theme/components/calendar-kit/components/calendar-day-picker/calendar-day-picker.component.ts
src/framework/theme/components/calendar-kit/components/calendar-days-names/calendar-days-names.component.ts
src/framework/theme/components/calendar-kit/services/calendar-month-model.service.ts
src/framework/theme/components/calendar/base-calendar.component.html
src/framework/theme/components/calendar/base-calendar.component.ts
src/framework/theme/components/calendar/calendar-range.component.ts
src/framework/theme/components/calendar/calendar.component.ts
src/framework/theme/components/datepicker/calendar-with-time.component.ts
src/framework/theme/components/datepicker/datepicker.component.ts
src/playground/with-layout/datepicker-with-format/date-timepicker-dynamic-inputs-showcase.component.html
src/playground/with-layout/datepicker-with-format/date-timepicker-dynamic-inputs-showcase.component.ts
src/playground/with-layout/datepicker-with-format/datepicker-dynamic-inputs-showcase.component.html
src/playground/with-layout/datepicker-with-format/datepicker-dynamic-inputs-showcase.component.ts
src/playground/with-layout/datepicker-with-format/datepicker-with-format.module.ts
src/playground/with-layout/datepicker-with-format/rangepicker-dynamic-inputs-showcase.component.html
src/playground/with-layout/datepicker-with-format/rangepicker-dynamic-inputs-showcase.component.ts

feat: add firstDayOfWeek to datepickers

---

CHANGELOG.md
docs/versions.json
package-lock.json
package.json
packages-smoke/package-lock.json
packages-smoke/package.json
src/framework/auth/package.json
src/framework/bootstrap/package.json
src/framework/date-fns/package.json
src/framework/eva-icons/package.json
src/framework/firebase-auth/package.json
src/framework/moment/package.json
src/framework/security/package.json
src/framework/theme/package.json

chore: 13.0.0

---

src/framework/theme/components/tree-grid/tree-grid.component.ts

Since Angular 17.1.0 and above the NbTreeGrid component wasn't working due to this missing CDK_TABLE provider and was giving this error: NullInjectorError: No provider for InjectionToken CDK_TABLE!
This fixes the issue where we get a NullInjectorError: No provider for InjectionToken CDK_TABLE! while using Nebular 13 & 14 in combination with Angular 17.1.0 and above. See issue: https://github.com/akveo/nebular/issues/3241

fix(NbTreeGrid): Add a provide for CDK_TABLE
